### ISSUE TITLE
Disable Invite Users button on organisation page until email address is entered

### ISSUE THREAD

**Issue by TheSussex** [openfoodfacts/openfoodfacts-server#10130]
### What
When a producer clicks on the` Invite Users ` button without entering any email in the form, it redirects to the home page

### Steps to reproduce the behavior

1. Go to 'https://world.pro.openfoodfacts.org/'
2. Log in to with you producer details
3. Click on the dropdown beside the User's name in the far right and select 'Edit your organisation profile'
4. Click on the `Invite Users` button without entering any email address in the box, it will redirect you to the organisation's home page.

Here is [a link to the conversation on Slack](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1712567629630809).

### Expected behavior
The ` Invite Users ` button should be disabled until at least one email address has been entered.

### Why
This will help improve user experience because with the current flow, the producer might not know that no action was performed.
 
### Type of device
Browser: Google Chrome (Version 123.0.6312.87)

**Comment by teolemon** [comment]
**Issue Title:** Disable Invite Users button until email address is entered

**Component:** Server

**Description:**

- When a producer clicks on the `Invite Users` button without entering any email in the form, it redirects to the home page.
- This can be confusing for producers and may lead them to believe that the invitation was sent successfully.

**Steps to Reproduce:**

1. Log in to openfoodfacts.org as a producer.
2. Click on your user name in the top right corner and select "Edit your organisation profile".
3. Click on the `Invite Users` button without entering any email address in the box.

**Expected Behavior:**

- The `Invite Users` button should be disabled until at least one email address has been entered.

**Impact:**

- Improves user experience by ensuring that producers are aware that no invitation was sent.

**Technical Details:**

- The issue is likely caused by a missing validation check on the server-side.
- The server should check if at least one email address has been entered before processing the invitation request.

**Suggested Solution:**

- Add a server-side validation check to ensure that at least one email address has been entered before processing the invitation request.
- Disable the `Invite Users` button until at least one email address has been entered.

**Additional Notes:**

- This issue was discussed on Slack: https://openfoodfacts.slack.com/archives/C02LDQDDD/p1712567629630809
- This issue should be prioritized as it can be confusing for producers and may lead to wasted time and effort.
