### ISSUE TITLE
Product Name does not appear in JSON API response

### ISSUE THREAD

**Issue by domigmr** [openfoodfacts/openfoodfacts-server#10636]
### What
- when making a request to the API, the responding JSON does not contain the title of the page or the name of the product.
- for example, for product 5420038407636 you might expect 'Huile d'olive' to be included in the JSON response somewhere, but it is not
- there is a field 'generic_name_en' or 'generic_name_fr' - but this is only sporadically completed, and sometimes the description is quite vague.

### Why
- I am scanning the barcodes of my groceries into a google sheet which then makes the request. By having the names in there, I will be able to more easily see which products are missing information in the OFF database.

### Type of device
- REST-API

### Number of products impacted
all

**Comment by hangy** [comment]
Could you provide a sample REST URL of the product that you're fetching? https://world.openfoodfacts.org/api/v3/product/5420038407636 contains the name in the fields `product_name` and `product_name_fr`. Note that the `product_name` will be in the product's main language (field `lang`/`lc`), so that checking for the existence of a `product_name_fr` field might be interesting, if you want to prioritize French over other languages.

**Comment by domigmr** [comment]
@hangy you are completely right, I somehow missed that key! That solves my problem! Thank you very much.
