### ISSUE TITLE
Detect vegetal oil in other languages

### ISSUE THREAD

**Issue by woshilapin** [openfoodfacts/openfoodfacts-server#107]
Since the ingredients list may be written in different languages (language of the packaging), the "vegetal oil" may be written in a different language.  At the moment, if it appears in German for example, "Pflanzliche Oel", there is no warning message like the one you can see here http://fr.openfoodfacts.org/produit/3387390124439/nestle-crunch-cereales (with a big palm tree).

**Comment by hangy** [comment]
This depends on #224. Currently, the lists `ingredients_from_palm_oil.txt` and `ingredients_that_may_be_from_palm_oil.txt` do not support translation, so that it would be best to taxonomize all ingredients first and add a property like `may_be_from_palm_oil:en:true` to the taxonomy. This tag could then be used to look up matching ingredients in the ingredient list's language.

**Comment by teolemon** [comment]
Stumbled on that bug recently. @stephanegigandet

**Comment by teolemon** [comment]
https://en.wiki.openfoodfacts.org/Global_palm_oil_taxonomy

**Comment by aleene** [comment]
Should be covered by #522.

**Comment by teolemon** [comment]
fixed. closing @stephanegigandet @aleene
