### ISSUE TITLE
Release v2.45.0 broke the ability to add nutrients and other features are showing issues

### ISSUE THREAD

**Issue by October-Food-Facts** [openfoodfacts/openfoodfacts-server#10861]
Release [v2.45.0](https://github.com/openfoodfacts/openfoodfacts-server/releases/tag/v2.45.0) broke some of the site's functionalities.

The ability to add nutrients, such as vitamins and minerals, is broken. The input field in the screenshot with the placeholder text "Add a nutrient" does not work properly anymore as of the latest release.
![Image](https://github.com/user-attachments/assets/dfbd153c-de1f-4322-8118-eec695811c13)

The checkbox with "Nutrition facts are not specified on the product" isn't behaving properly as it was anymore. When toggled, it no longer collapses (hides) its respective section in full as it did before, even after saving changes and returning to edit again.

The checkbox with "Nutrition facts are specified for the product as sold" also isn't behaving properly as it was anymore, even though it's hard to tell. It appears that when it arrives unchecked by an app contribution, toggling it no longer opens up the nutrition table, making it impossible to fill-in values on it. The page has to be saved for the table to become available upon returning to edit again.

Furthermore, as of this release, one is unable to add Folksonomy properties, which stopped working. It seems similar to the nutrients issue because it involves dropdown suggestions.

The release also broke the Folksonomy panel layout, while it moved the search bar in table list pages to the left side, needing a bit of habituation to it.

**Comment by October-Food-Facts** [comment]
I updated this with more issues. :)

**Comment by jayaddison** [comment]
I encountered this problem earlier today, when attempting a daily data-quality task.

One thing I noticed in my Firefox developer console when taking a look for JavaScript errors: there was an error message about `uniqueSort` not being an available (jQuery) function.

It seems `uniqueSort` was removed from jQuery a long time ago, however the `jQuery-UI` library (used by OFF) provides some 'patch' functionality to insert a substitute for it (called a `polyfill` in JavaScript terminology).

That polyfill was disabled by default in `jQuery-UI` version 1.14, that we upgrade to recently (#10681) -- so I would guess that that is a possible candidate for what caused the error.

I don't know if that error could cause the entirety of this failure to load the nutritional prompts, but it seems possible.

The [upgrade guide mentions a `jQuery.uiBackCompat` setting](https://jqueryui.com/upgrade-guide/1.14/#reduced-jquery-support) that can be enabled -- that might provide a short-term fix, although it would be preferable to try to remove reliance on any long-removed jQuery features.

I'll try to investigate further soon.

**Comment by Valimp** [comment]
According to the Jquery ui documentation a file name was changed. I think that's where the problem comes from.
I'm going to investigate this JS import
[jQuery-ui documentation](https://jqueryui.com/upgrade-guide/1.13/#files-amp-directory-structure)

**Comment by Valimp** [comment]
we investigated with @raphael0202,

"Only the latest jQuery version within each major version of jQuery is supported. To make updates easier, we also run tests with a few other relatively recent versions, but we don't guarantee continued support for them in all jQuery UI releases in the 1.14.x line. Each jQuery UI version will document on which jQuery versions it was tested - both in the release blog post and in the changelog page at https://jqueryui.com/changelog/."

But current version of jQuery is 2.1.X when it should be 2.2.4
Moreover it seems that "foundation-sites" force jQuery version to 2.1.X and that need more works to fix that because of very old version of this dependencie (9years for the last update)

A quick fix is to downgrade jquery-ui version

**Comment by CharlesNepote** [comment]
> A quick fix is to downgrade jquery-ui version

Yes please. The lack of auto completion is very anoying for many contributors.

You can try other solutions later, but the quick fix should be applied IMHO.

**Comment by jusdekiwi** [comment]
Has anyone found a solution? :(

**Comment by jayaddison** [comment]
I tested this locally and was able to replicate the same problem.

Then I took a look at the source control history for `gulpfile.ts`, because I found a [report of a similar problem](https://github.com/struts-community-plugins/struts2-jquery/issues/89) on GitHub, and it related to the order in which dependencies are added (I didn't read the code of their eventual fix, but it did help to get ideas for what the problem might be).

Looking at the git logs, #10708 seemed relevant, so I tried reverting that, and it fixes the autosuggest problem when I test it locally:

https://github.com/user-attachments/assets/eb40f7dd-3167-4c0b-a982-9bc46db06988

I haven't yet confirmed that this repairs the Folksonomy engine functionality, but I will attempt to do that soon.  (there are some CORS errors that appear in my dev instance that I'll need to resolve first, I think)

I'll open a pull request with a revert for #10708 soon.

**Comment by jayaddison** [comment]
Release 2.47.0 containing the anticipated fix #10924 has been deployed to production, but I'm still unable to select nutrient names after they appear in the drop-down list.  So this issue does not appear to be resolved yet :/

Could we reopen the bugreport?

**Comment by jusdekiwi** [comment]
I've just checked and it works for the NF drop-down menus and for Folksonomy as well! Thanks! 🥳

**Comment by jayaddison** [comment]
Yep, I can confirm that nutrient selection is working for me now too 👍
