### ISSUE TITLE
Enable a token based auth for the mobile app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1204]
### What
- Enable a token based auth for the mobile app so that we don't have to store the password on the mobile devices and send them everytime.

### Part of
- #8919

**Comment by hangy** [comment]
As you may have noticed, I had started something like that in the [OpenID Connect branch](https://github.com/openfoodfacts/openfoodfacts-server/tree/oidc). For some reason, though, Perl always SEGFAULTs in one of the used Perl modules. It should be easy to finish this if anyone has an idea how to fix those Perl modules. 👍

**Comment by hangy** [comment]
I revisited this idea last weekend. Instead of re-implementing OIDC (as there seems to no good OIDC Identity Provider library for Perl - and is out of scope for this project), we could integrate [hydra](https://github.com/ory/hydra) with ProductOpener to get a verified OIDC IdP, and see whether the APIs users can be [verified](https://auth0.com/docs/api-auth/tutorials/verify-access-token) using [Crypt::JWT](https://metacpan.org/pod/Crypt::JWT).

**Comment by hangy** [comment]
Closing as a duplicate of #1596
