### ISSUE TITLE
Randomly adding new barcodes in the background (20000000xxxxx)

### ISSUE THREAD

**Issue by saihtaM** [openfoodfacts/openfoodfacts-server#129]
Sometimes while browsing the site, it makes you add new products without you even know it.

Here's a few:
2000000018345
2000000018346

Looks like some kind of a counter or something?

(Firefox on Windows, with LastPass as the only plugin that are touching the page)

**Comment by hangy** [comment]
Maybe some kind of browser prefetching? Every time /cgi/product.pl is called (even for non-logged in users and GET requests), a new product with this internal barcode structure is created. Maybe it would be best to limit data modifying actions to POST requests.

Related: 
* http://stackoverflow.com/a/786074/11963
* http://stackoverflow.com/a/786084/11963
* http://stackoverflow.com/a/786085/11963
* http://stephenwalther.com/archive/2009/01/21/asp-net-mvc-tip-46-ndash-donrsquot-use-delete-links-because

**Comment by hangy** [comment]
I added a [suggestion](https://bitbucket.org/openfoodfacts/product-opener/commits/c10f3ed807c9a2e929d4a243214fc51e05457044) on limiting the counter-based product creation to POST requests.

**Comment by hangy** [comment]
This should now be live on openbeautyfacts.org and openfoodfacts.org. Let me know if this solves the problem. :)
