### ISSUE TITLE
Keep the same UI language after clicking showing products from the whole world

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-server#1437]
**Summary:**
https://de.openfoodfacts.org changes to https://world.openfoodfacts.org, but better would be https://world-de.openfoodfacts.org

**Steps to reproduce:**
- Open https://de.openfoodfacts.org
- Click on "Entsprechende Produkte aus der ganzen Welt ansehen" (Show respective products from the whole world)

**Expected behavior:**
It should show international products with labels in the language previously chosen (supposedly for good reason).

**Observed behavior:**
It shows international products, but with English labels.

**Comment by stephanegigandet** [comment]
Related code: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Display.pm#L4035

$request_ref->{world_current_link} needs to be built with the $lc language code instead of "en", and then the subdomain needs to be world-[language code].openfoodfacts.org (e.g. world-de.openfoodfacts.org )

**Comment by Fienne** [comment]
@stephanegigandet I've gone through the whole page but couldn't find the "Entsprechende Produkte aus der ganzen Welt ansehen" (Show respective products from the whole world) sentence. So I'm unable to tackle the issue.

**Comment by alexgarel** [comment]
@Fienne most of the time, we use ids for messages to handle translation. The sentence here is in "po/common/de.po" and it has id "view_products_from_the_entire_world" that you may find in the code (or a template).

But starting from the link might be difficult, because you have then to understand where the router will route the request. So @stephanegigandet already points to the right point in code. See https://github.com/openfoodfacts/openfoodfacts-server/issues/1437#issuecomment-1081894823
