### ISSUE TITLE
Industrialize images and data import scripts, create standard CSV format

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1528]
More and more producers are willing to send us data and pictures for their products. So far they have been giving us the data and images in a wide variety of formats like Excel, CSV, XML, and we have developed some custom import scripts for each of them, with a lot of copy and paste.

We are starting to industrialize that process by:

1. Creating a standard CSV file format for OFF imports, described in https://world.openfoodfacts.org/producers 
2. Creating an import_csv_file.pl script to import data in this format
3. Creating an Import.pm module with functions that make it easy to validate and normalize data in this CSV format, and to easily convert other formats to our standard format.
4. Using the Import.pm module, creating conversion scripts for big producers to convert their data to the CSV format.

**Comment by NerOcrO** [comment]
Why not in JSON directly?

**Comment by stephanegigandet** [comment]
> Why not in JSON directly?

Producers have their data in various formats, usually Excel files, sometimes XML dumps. It's easier to ask them for a CSV file, to review it etc. Their data is usually not very well structured, formated etc. Most of them won't be able to produce JSON files.

**Comment by hangy** [comment]
Maybe use something that has a validatable schema. I don't know if [CSV Sschema](http://digital-preservation.github.io/csv-schema/csv-schema-1.1.html) is well-known enough, but it might be a start.

**Comment by CharlesNepote** [comment]
@hangy and @stephanegigandet a few months ago I made a [comparison between CSV schemas](https://docs.google.com/spreadsheets/d/1-UVuyb-BGkDUsEF6tqffjZtz4bq3dC8fX6RTZriTZBY/edit#gid=0) (in french). Frictionless data specs are simpler and implemented in many languages (not sure about Perl). Just check Table schema: https://frictionlessdata.io/specs/table-schema/

I created a simple spec for babies first names: https://github.com/CharlesNepote/liste-prenoms-nouveaux-nes
This spec is based on Table Schema with little enhancements to automatically produce a documentation of the spec. That way, all the work is done on the spec (in JSON) and the documentation is generated.
On my repository I use a [YAML file](https://github.com/CharlesNepote/liste-prenoms-nouveaux-nes/blob/master/goodtables.yml) to validate my data with the [Goodtable validator](http://goodtables.io/).

With Open Data France, Jailbreak and others we've also build a validator in french based on frictionless specs:
https://go.validata.fr/

Creating a spec is big stuff: months at least because you have to discuss with all different producers and reusers. I also produced a [document to learn how to produce a good data standard](https://docs.google.com/document/d/1zMHb_98c5XA7yGKnL4u7-WFmA5BNTczJ3kBHCoWmtW4/edit) (also in french).

Of course I can help on this topic.

**Comment by teolemon** [comment]
I'm closing this issue, as it is fixed by the Producer Platform
