### ISSUE TITLE
Moving a product to OPFF/OBF… is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1624]
```Software error:
Undefined subroutine &ProductOpener::Products::get_collection called at /srv/off/lib/ProductOpener/Products.pm line 269.
For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.```

**Comment by hangy** [comment]
The only reason I can think of, is that `ProductOpener::Data` was not deployed or `ProductOpener::Products` was only deployed partly. `ProductOpener::Data` is referenced in https://github.com/openfoodfacts/openfoodfacts-server/blob/5558ed8dda0d37a5c4363a4b5b17e476e1a0611c/lib/ProductOpener/Products.pm#L71, so that `get_collection` should be available.

**Comment by stephanegigandet** [comment]
I just moved a product from OFF to OBF to OPF to OPFF and back to OFF. Everything seems to work now. :)
