### ISSUE TITLE
Impossible to set an image as Brazilian

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1752]
![image](https://user-images.githubusercontent.com/1689815/57048771-a5ca9000-6c75-11e9-9125-29002a2a80f6.png)

**Comment by hangy** [comment]
Yes, that's because OFF doesn't support language tags/variants. Please send the image as "imgupload_other_pt" instead.

**Comment by teolemon** [comment]
We have buggy clients in the wild. We need a fix anyway. 
@stephanegigandet has made a similar fix for some other part of the API

**Comment by stephanegigandet** [comment]
I have not been able to replicate the bug, when I set my language to Portuguese Brazilian, I can create a product with an image, or add an image, and it's correctly set to PT. e.g. https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3255430001319

Has this already been fixed in beta on the app side?

**Comment by stephanegigandet** [comment]
If you can replicate the bug, does this happen only for the "other" images, and not front / ingredients / nutrition?

**Comment by teolemon** [comment]
fixed
