### ISSUE TITLE
Product transfer to OPFF seems broken (images broken)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1795]
Product transfer to OPFF seems broken (images broken)
Product is transferred ok but images are not.

**Comment by stephanegigandet** [comment]
Found the issue, it's because OFF images are on /srv2 and OPF still on /srv.  The File::Copy move function we use does not work if it can't just rename the directories (in fact it looks like it's not supposed to work on directories at all).

One option is to use https://metacpan.org/pod/File::Copy::Recursive#dirmove() which will copy the files and then remove the directory. Which is a bit of an overkill if we are on the same file system. Another option is just to call the system's "mv old new"

**Comment by VaiTon** [comment]
This can be closed as fixed by #1828. @stephanegigandet
