### ISSUE TITLE
No link to Hunger Game

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#1896]
There is no link on the main page to access `/hunger-game`

**Comment by CharlesNepote** [comment]
It can be easy to solve, of course. But I think we need to better think at Hunger Game usages and potential issues.

Why make efforts to promote Hunger Game to a greater audience? Why Hunger Game should be a priority?
- Hunger Game allows to complete thousands of products per user per hour
- MANY products don't have Nutri-Score because of lacking category
- Hunger Game helps to train AI

Why not launching/promoting Hunger Game to a greater audience? What are the potential issues?
- One could quickly fill the database with false data (example: always pressing yes)
- Playing too fast with Hunger Game can lead to errors
- Sometimes robotoff provide too large categories such as "water" where we could answer "natural water"

Ways to solve issues:
- a. identify who answers the question (but it doesn't prevent first issue).
- b. a + restrict to users older than xx months? with more than 50 edits? xx months AND 50 edits?
- c. Valid an answer after more than 3 identical answers by 3 different users; 6 users if one user give a different answer; but we would lost people playing for their personal counter
- d. c + create a new category for people contributing to an edit (to prevent (c) issue)? or create a parallel counter for people playing with Hunger Game?
- e. "beginners" role that need to valid 100 true answers before their answers are taken in account without confirmation 

Solution b, could be a good start.

**Comment by teolemon** [comment]
It was added in the Power User Script. The Power User Script is going to be integrated on the web (no need to install it anymore). 
We could make the link visible to all logged in users.

**Comment by VaiTon** [comment]
> One could quickly fill the database with false data (example: always pressing yes)

We could take a number of votes before applying the edit.
Eg. user1 voted no, user2 voted yes, user 3 voted yes so it is applied

**Comment by CloCkWeRX** [comment]
> Playing too fast with Hunger Game can lead to errors

It'd be nice to have an easy Undo; or even just render a log of recently applied answers. Most of the time I'm logged in and can go to the recently updated list of products by me; or the global list if I make a mistake; but it's a number of clicks.

From a UX perspective, it would also be interesting to get a more positive reward for "skip" shown to the user - its often just as valid particularly with the edge cases.

**Comment by teolemon** [comment]
I believe those concerned have all been addressed, and that Hunger Games is ready for prime time. 
I'm closing this issue
