### ISSUE TITLE
New popularity facet with top 10 / 100 / 1000 etc. popular products based on unique scans

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#1943]
In order to be able to quickly review the quality / compute stats etc. for popular products, we are going to add a new popularity facet.

The facet will initially have values related to the number of scans by unique ips made with the OFF official app:

- top-10-scans-2019 (same for top 50, 100, 500, 1000, 5000 ... 100 000)

We could possibly use the same facet for other measures of popularity. (e.g. scans by other apps, sales figures from some stores, stock data from food banks, searches and views on the OFF web site etc.)

When we have a proper scans database (as described in #1501), we will populate the /popularity facet through the scans database.

In the short term, we will use the scanbot.pl log processing script to populate the facet.

**Comment by teolemon** [comment]
quick and 80% efficient for 20% effort 👍

**Comment by teolemon** [comment]
outside the scope, but can you add another facet: 
`countryscan/scanned-3-times-in-{country}`

**Comment by CharlesNepote** [comment]
@teolemon 3 times is few isn't it? I would say 5, 7 or 10 times. And you must precise X times by different people/IP on a different day, isn't it?

@stephane is it possible to add:
- /scans/never # products never scaned except the day they where entered in the database; will allow to identify false products, wrong barcode recongintion, etc.
- /scans/never-since-1-year # (or 2 years?) will allow to identify products that are not sold anymore
- /scans/less-than-7 # will allow see products that could be false or not sold anymore
- /scans/less-than-7-since-1-year
- /scans/less-than-0-dot-01-percent (or a thing like that) # will allow to answer to "trolls" based on rarely scanned products
 
We should discuss a little bit the interface, but if you prefer to go quick, we can discuss later.

The good thing should be to document **before** coding ;-)

**Comment by stephanegigandet** [comment]
At this point, we have 250k scans from 2019 (only scans from the new Android app), out of 900k products. So there will be 650k products without scan data at all. So the "never" scans values may not be very useful.

We have some scan data from previous years, but it's not directly comparable (it contains all API calls, including bots, searches etc.). We could load it to populate different values (e.g. top-1000-api-2018), but it would need cleaning to make sure we remove bots etc.

This bug is a quick and dirty fix to get a useful popularity facet, it is not a replacement for the scan database that will make many more metrics etc. possible.

**Comment by teolemon** [comment]
3 is low because we don't have a lot of certified volume from the app, but it was the threshold we used to add countries in the old times. 
It would enable me to mass add countries of sales using the mass-edit extension, and mass correct the main language

**Comment by stephanegigandet** [comment]
https://world.dev.openfoodfacts.org/popularity is being populated on the dev server.

There are facets like:

https://world.dev.openfoodfacts.org/popularity/top-1000-scans-2019 -> top 1000 products

https://world.dev.openfoodfacts.org/popularity/at-least-10-scans-2019

https://world.dev.openfoodfacts.org/popularity/at-least-5-de-scans-2019 -> Scanned at least 10 times in Germany

https://world.dev.openfoodfacts.org/popularity/top-country-ch-scans-2019 -> Products for which the country with the most scans is Switzerland

Like other facets, the value can be negated:

https://world.dev.openfoodfacts.org/popularity/-at-least-5-scans-2019 -> Products that have less than 5 scans

**Comment by stephanegigandet** [comment]
Deployed in production. Updates are currently not automated.

To update counts:

grep "Official Android App" nginx.access2.log | grep Scan > android_app.log
./scanbot.pl < android_app.log
