### ISSUE TITLE
Main language of products mistakenly set to Zulu (zu) for some products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2063]
kiliw*b seems to be sending zulu code names in some specific cases. 
https://world.openfoodfacts.org/product/3564707143608/mayo-moutarde-dijon-bio-boc-marque-repere

**Comment by hangy** [comment]
I think this could be a bug in ProductOpener instead of kiliweb. I'm trying to debug the failing tests on #1696 right now, and have put some `print STDERR` statements into the source to find out what's wrong. Inside `ProductOpener::Tags::canonicalize_tag`, I'm using `print STDERR "$tag - $lc\n";`, and for some reason, it prints `en:non-vegan - zu` for the unit test in `t/tags.t`. The unit test itself does not set `$lc = 'zu'` anywhere, so there seems to be some kind of initialization issue.

**Comment by stephanegigandet** [comment]
$lc is set by Display::init()

If Display::init() is not called, then $lc could be anything, as you remarked, it's probably set to "zu" because during initialization of one of the modules there are loops on $lc

**Comment by VaiTon** [comment]
> $lc is set by Display::init()
> 
> If Display::init() is not called, then $lc could be anything, as you remarked, it's probably set to "zu" because during initialization of one of the modules there are loops on $lc

Maybe because it is the last value alphabetically

**Comment by stephanegigandet** [comment]
I think this happens / happened for imports, it's mostly for Scamark, Carrefour and foodrepo products: https://world.openfoodfacts.org/language/zulu/brands

**Comment by stephanegigandet** [comment]
It is indeed a bug in the import_csv_file.pl script, the lc field was correctly set, but the lang field was set to "zu". The ingredients_text_fr / de etc. fields and front_fr images etc. were correctly set, but the main language of the product was set to Zulu. Then other edits by Yuka or others could send front_zu images.

I verified the bug and fixed it in import_csv_file.pl

I'll also make a script to fix the existing products.

**Comment by stephanegigandet** [comment]
Products to fix:

> db.products.count({ lang : "zu" })
4837
> db.products.count({ lang : "zu", lc : "fr" })
2391

**Comment by stephanegigandet** [comment]
Command to fix the product that actually have some zu values (because they were modified after the import), and that are visible with /language/zulu

./update_all_products.pl --query languages_tags=en:zulu --user_id fixbot --comment "removing wrong language (zulu)" --fix-zulu-lang

This won't find the products that have just the lang=zu. We don't have an index for the lang field though, I need to remove the timeout in the query.

**Comment by stephanegigandet** [comment]
in Data.pm, to remove the timeout:

sub get_mongodb_client() {
	if (!defined($client)) {
		$log->info("Creating new DB connection");
			$client = MongoDB::MongoClient->new(
				host => $mongodb_host,
				connect_timeout_ms => 100000,
				socket_timeout_ms => 100000,
			);

I just need it once, so I won't make an option.

**Comment by stephanegigandet** [comment]
After removing the timeout:

./update_all_products.pl --query lang=zu --user_id fixbot --comment "removing wrong language (zulu)" --fix-zulu-lang

**Comment by stephanegigandet** [comment]
ok in prod the timeout was not needed, the dev server is too slow.

The fix is deployed and the 4800 products have been fixed.
