### ISSUE TITLE
huile d'origan parsing

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#2118]
**Describe the bug**
It seems there is a parsing error in this string "huile d'olive vierge, origan", which is listed as "huile d'origan".

**To Reproduce**
All in this list https://world.openfoodfacts.org/editor/systeme-u/ingredient/fr:huile-d-origan

**Comment by aleene** [comment]
Similar: https://world.openfoodfacts.org/editor/systeme-u/ingredient/fr:huile-de-cacao-maigre-en-poudre

**Comment by stephanegigandet** [comment]
Good catch, I'm fixing it.

**Comment by stephanegigandet** [comment]
That was because I had a list of prefixes (like "huile", "arômes") and prefixes ("palme, tournesol, fraise, cacao"), and the suffixes were not specific to prefixes, so "huile de palme, fraise" was turned into "huile de palme, huile de fraise". We might still have a few false positives, but they should be much more rare.

**Comment by stephanegigandet** [comment]
Fixed.
