### ISSUE TITLE
Json API consistency

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#2150]
**Describe the bug**
I am extending my app to allow the translation of ingredients based on the detected ingredients and the taxonomy. I noticed that for a specific field not always the same data is offered. 

The various representations of a field should offer the same data (type and meaning).

**To Reproduce**
Any product json.

**Expected behavior**
The following key-types seem to occur:
* field - the data in string format. This contains all the data as a single string. If the data is originally a list of strings, it will be comma separated.  (ingredients_text) Is this for the main product language.
* field_text_XX - the data in string format as entered by the user in language XX. Only available for ingredients. Is missing for other fields.
* field_original_tags - the data as a list of strings. Each string is normalized through a corresponding taxonomy. Normalizing means getting rid of synonyms and translations (only for ingredients). (for entry dates another meaning is used)
* field_tags - the data as a list of strings. This is the same as the field_original_tags (if available) but with all the parents found in the taxonomy (only the ingredients work like this). 
* field_hierarchy -  the same as field_tags, but some have it and some not (stores)
* field_from_user - ? (used for traces and allergens). Why a separate one? Could be the same as field
* field_from_ingredients - ? (used for traces and allergens)

It seems not very consistent.

**Comment by stephanegigandet** [comment]
ingredients_text -> it is the same as the ingredients_text_XX field for the main language.
(same for other language specific fields like product_name, generic_name etc.)

field_tags / field_hierarchy can have different sort orders. That's because the fields are displayed differently. For ingredients for instance, it's important to have the ingredients in the order of the ingredients text. For categories, we order the category by specificity.

allergens_from_user / from_ingredients : this is to distinguish allergens that were extracted automatically from the ingredient list, and the ones that users entered in the allergens field. It is useful to keep both. The combined result is saved in allergens_tags

So most of those differences are intended.

**Comment by aleene** [comment]
Maybe this can be added to the documentation as well.
I am missing some fields from a completeness point of view. Not sure whether they are worthwhile. Still discovering hat I could use these fields for. At the moment the user has the possibility to look at them.
To be continued....
