### ISSUE TITLE
Autorotate bot issue

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2162]
![image](https://user-images.githubusercontent.com/1689815/62824736-8d3a1200-bba2-11e9-8f99-1e06f33ee07f.png)

**Comment by stephanegigandet** [comment]
What issue?

**Comment by teolemon** [comment]
@stephanegigandet The autorotate bots seems to have deleted the category ?

**Comment by teolemon** [comment]
in some cases, it added a category ?
https://world.openfoodfacts.org/product/8410032002866/atun-claro-al-natural

**Comment by hangy** [comment]
The bot is run as a part of [update_all_products.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/97bdb87e11599086c44616b684f632608197c158/scripts/update_all_products.pl). If some categories are changed, that could be caused by taxonomy changes that hadn't been reflected on the product, yet. Probably not a bug.

**Comment by stephanegigandet** [comment]
@hangy is right, that's probably just a taxonomy change. Which product was it?

**Comment by VaiTon** [comment]
> 
> 
> The bot is run as a part of [update_all_products.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/97bdb87e11599086c44616b684f632608197c158/scripts/update_all_products.pl). If some categories are changed, that could be caused by taxonomy changes that hadn't been reflected on the product, yet. Probably not a bug.

The displayed user is the autorotate bot. That's not intended behavior.

**Comment by hangy** [comment]
> > The bot is run as a part of [update_all_products.pl](https://github.com/openfoodfacts/openfoodfacts-server/blob/97bdb87e11599086c44616b684f632608197c158/scripts/update_all_products.pl). If some categories are changed, that could be caused by taxonomy changes that hadn't been reflected on the product, yet. Probably not a bug.
> 
> The displayed user is the autorotate bot. That's not intended behavior.

I don't think this can be suppressed in a useful way, right now. The same will happen when anything is changed via the API. For example, if someone calls `add_labels=foobar` and if there are pending category changes (because an of updated taxonomy), then this would be done implicitly by ProductOpener.

**Comment by stephanegigandet** [comment]
As @hangy says, the history change is not specific to the autorotate bot. I unfortunately did not find a good way to avoid that.

Closing the issue.
