### ISSUE TITLE
Remove colors from additives

### ISSUE THREAD

**Issue by Slawek234** [openfoodfacts/openfoodfacts-server#2187]
I noticed that in the French language version, harmless E-additives are marked green. 
In my opinion, it looks great, and in the other language versions it could have been applied.
<a href='https://postimg.cc/rKcG76Gg' target='_blank'><img src='https://i.postimg.cc/rKcG76Gg/Pas-ou-peu-toxique.jpg' border='0' alt='Pas-ou-peu-toxique'/></a>

**Comment by hangy** [comment]
The way that the `level` used to determine the colour of the additives is a bit … tricky. This information is currently stored separately for each language, and is detected from some HTML files in the `lang` directory. For example, https://github.com/openfoodfacts/openfoodfacts-server/blob/9d1df5890699bc66f35286569b46fdceae24a8dd/lang/fr/additives/e330.html#L16 sets `$tags_texts{fr}{additives}{e330} = 1;` because of `class="level_1"`

@stephanegigandet @teolemon Can you elaborate on why this is language-dependent? At a glance, I can find no reason why https://fr.openfoodfacts.org/product/3250391337491 would display the additive as green, while https://fr-en.openfoodfacts.org/product/3250391337491 doesn't.

**Comment by stephanegigandet** [comment]
@hangy @Slawek234 The color for additives is a feature that we are planning to remove, as it's very hard to know if any additive is harmless. (in theory, if they are authorized, then they are harmless). Only a few additives had a color, it's something I did back in 2012, and I stopped because it was very hard to get reliable info on additives.
