### ISSUE TITLE
Cannot build npm 6.12.0

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#2476]
### Description of the bug
`npm install` gives error when building with npm 6.12.0 and node v12.13.0

### To Reproduce
1. Install [Node v12.13.0](https://nodejs.org/en/blog/release/v12.13.0/)
2. Try to build the module
3. See error

### Desktop (please complete the following information):
 - OS: Windows 10 Pro

### Logs
```
PS C:\Users\***\openfoodfacts-server> npm install
npm ERR! code 1
npm ERR! Command failed: git checkout ^2.2.12
npm ERR! error: pathspec '^2.2.12' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2019-10-23T20_23_03_750Z-debug.log
```

[2019-10-23T20_23_03_750Z-debug.log](https://gist.github.com/VaiTon/2fea096fe4b50f349cdd394e95db99d2)

**Comment by hangy** [comment]
This might be caused by some of the dependencies, which are specified in a repository format: https://github.com/openfoodfacts/openfoodfacts-server/blob/1a26b07e47cc0056e8e325391b261cc3b8f6f2f7/package.json#L39-L50

Note that we currently use [yarn](https://yarnpkg.com/) to install packages and only have a [yarn.lock](https://github.com/openfoodfacts/openfoodfacts-server/blob/1a26b07e47cc0056e8e325391b261cc3b8f6f2f7/yarn.lock) to fix dependency versions. If we wanted to migrate to npm (which could be a good idea in the long run), we'd need to fix/update/change those dependencies. Right now, I wouldn't expect npm to install our dependencies correctly.
