### ISSUE TITLE
Paginate /ingredients /brands and /codes

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#262]
The /ingredients /brands and /codes are booming in size, degrading performance on slower laptops.

Paginating them in 2 or 3 pages would solve the issue.

**Comment by stephanegigandet** [comment]
If we paginate, we can't use the datatables filtering and sorting though. Unless there's a newer version with some sort of pagination /lazy loading support.

**Comment by teolemon** [comment]
There's something horribly wrong going on the http://fr.openfoodfacts.org/codes page due to bogus entries

**Comment by hangy** [comment]
DataTables does support [server-side processing](https://datatables.net/examples/server_side/) with several customization options and deferred loading.

Would SEO be an issue? Right now, the tables are completely indexed by search engines, and moving to a purely AJAX based table would most likely change that.

**Comment by hangy** [comment]
I experimented with this a little bit on the `issue/262` branch. While server-side processing is possible, and we could return data in a correct format for DataTables, it would not be possible to use MongoDBs sorting and filtering as well as paging, because the product only has a `labels_tags` property that contains label ids like `en:gluten-free`, so that ordering by the French `sans gluten` would put it on a completely wrong page. Since the translations are only stored in `sto` files and available in a processed form in-memory in the Perl/CGI process, there's no easy way to switch on pagination and support the full taxonomy right now.

**Comment by stephanegigandet** [comment]
Regarding SEO: I think it's fine if we don't have huge lists of tags. Those tags are also linked in product pages. We could also generate sitemap xml files with all the pages we want indexed.

Regarding the sorting / filtering: we could implement it in the Perl code, which would require a lot of processing on all entries, but those kind of queries would probably be relatively rare, as they would be from actual users. I'm guessing that currently, most of the page views for lists of tags are from search engine crawlers.

**Comment by stephanegigandet** [comment]
@hangy : regarding the filtering part, we already have a part of it available.
e.g. https://fr.openfoodfacts.org/labels?filter=gluten --> Perl will process the mongodb results with the taxonomy, and it will return "Sans gluten".

**Comment by hangy** [comment]
> @hangy : regarding the filtering part, we already have a part of it available.
> e.g. https://fr.openfoodfacts.org/labels?filter=gluten --> Perl will process the mongodb results with the taxonomy, and it will return "Sans gluten".

Yes, but it will also force the server to load everything in memory and sort it for every request/page (unless we store the whole filtered and sorted list in memcached - which could be a bit too large objects?). I'm not sure if that's efficient enough...

**Comment by syl10100** [comment]
![image](https://user-images.githubusercontent.com/45109552/78684705-1734a900-78f1-11ea-92d2-319a01dd4877.png)
These are stats about heavy facets. 
For instance, we can see that https://world.openfoodfacts.org/ingredients returns more than 700000 distincts ingredients_tags and that 83% of these ingredients_tags are present in only one product.
So what is the purpose of this ? Is it necessary to have a full list of all ingredients_tag ?
Why not adding a limit stage ({ "\$limit" => 20000 }) to the aggregation in order to reduce the number of lines returned ?

**Comment by syl10100** [comment]
![image](https://user-images.githubusercontent.com/45109552/79589496-c6ce0000-80d5-11ea-9faa-6a8b4e387c59.png)
Here are the size of each HTML page. We can see that for https://world.openfoodfacts.org/ingredients the page size is 120MB. Which is way too much !
I propose to add a pagination and limit 10000 lines par page.
https://world.openfoodfacts.org/ingredients will return the TOP 10000 ingredients
https://world.openfoodfacts.org/ingredients/2 will return the next 10000 ingredients
and so on...
This way, each HTML page size will be less than 2MB.
What do you think about this ? @stephanegigandet @teolemon @hangy

**Comment by thadk** [comment]
I noticed that `https://world.openfoodfacts.org/ingredients.json/2` works as well to page through the ingredients in number-of-product descending order for the JSON result page instead of the HTML result page.

**Comment by yangar** [comment]
https://world.openfoodfacts.org/ingredients.json
Return a 504 Gateway Time-out, i guess pagination should be implemented!
