### ISSUE TITLE
Netherland: "6" products instead of 6000

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#2665]
https://nl.openfoodfacts.org/

![](http://i.imgur.com/519x59Q.png)

**Comment by hangy** [comment]
I saw this too, but it's gone now. Could it be that it only errored for exactly 6000 products? ![image](https://user-images.githubusercontent.com/87124/69833462-514fb900-1234-11ea-976e-a9e0ec8c5354.png)

**Comment by CharlesNepote** [comment]
> I saw this too, but it's gone now. Could it be that it only errored for exactly 6000 products? 

Hmmm... interesting question, but I would be surprised. Should we close the bug or maybe you an idea on how to reproduce?

**Comment by stephanegigandet** [comment]
> you an idea on how to reproduce?

Let's delete 81 products. ;)

**Comment by stephanegigandet** [comment]
In fact I think I know what happened, this is because of this:

$html_count .= sprintf(lang("n_products"), $decf->format($count)) ;

We used to expect a number, before the formatter was used.

msgid "%d products"

It was changed to "%s products" but it looks like it didn't get propagated to the nl.po file until 25 days ago.

I'm going to close this.
