### ISSUE TITLE
Bad Gateway when sending requests to Robotoff

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#2820]
I experienced Bad Gateway when sending requests to Robotoff.
After investigation, I found that the dev server (when robotoff is deployed) does not always receive the request. These Bad Gateway are probably due to connectivity issues between the two servers.

Currently, the production server is used as a proxy:
request --> prod nginx (openfoodfacts.org) --> dev nginx -> robotoff API

Sending the requests directly to the dev server would allow to avoid some of these Bad Gateway, and improve latency. Furthermore, the prod server would not be a single point of failure for the robotoff service.

**Comment by hangy** [comment]
Maybe just add a CNAME for the Robotoff API subdomain? It shouldn't matter too much if it runs on a different port …

**Comment by stephanegigandet** [comment]
There are errors indeed:

off@off1:/srv/off/logs$ tail -n 5 /srv/off/logs/robotoff.nginx.error2.log
2020/01/10 11:35:34 [error] 203839#203839: *22294 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 88.191.250.206, server: robotoff.openfoodfacts.org, request: "POST /api/v1/webhook/product HTTP/1.1", upstream: "http://51.77.65.233:5500//api/v1/webhook/product", host: "robotoff.openfoodfacts.org"
2020/01/10 11:35:37 [error] 203845#203845: *12644 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 89.3.3.139, server: robotoff.openfoodfacts.org, request: "GET /api/v1/questions/8711521916931?lang=en HTTP/2.0", upstream: "http://51.77.65.233:5500//api/v1/questions/8711521916931?lang=en", host: "robotoff.openfoodfacts.org", referrer: "https://world.openfoodfacts.org/product/8711521916931/ekoplaza"
2020/01/10 11:35:44 [error] 203838#203838: *22601 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 88.191.250.206, server: robotoff.openfoodfacts.org, request: "POST /api/v1/webhook/product HTTP/1.1", upstream: "http://51.77.65.233:5500//api/v1/webhook/product", host: "robotoff.openfoodfacts.org"
2020/01/10 11:35:44 [error] 203838#203838: *22604 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 88.191.250.206, server: robotoff.openfoodfacts.org, request: "POST /api/v1/images/import HTTP/1.1", upstream: "http://51.77.65.233:5500//api/v1/images/import", host: "robotoff.openfoodfacts.org"
2020/01/10 11:35:45 [error] 203838#203838: *22624 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 88.191.250.206, server: robotoff.openfoodfacts.org, request: "POST /api/v1/images/import HTTP/1.1", upstream: "http://51.77.65.233:5500//api/v1/images/import", host: "robotoff.openfoodfacts.org"

But neither prod or dev is overloaded right now, so the issue is probably somewhere else.

**Comment by stephanegigandet** [comment]
"request --> prod nginx (openfoodfacts.org) --> dev nginx -> robotoff API"

--> it doesn't go through dev nginx currently, it goes directly to port 5500:

    location / {
        #proxy_pass http://robotoff.bournhonesque.eu:80/$request_uri;
        proxy_pass http://dev.openfoodfacts.org:5500/$request_uri;
        #proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 90;
        client_max_body_size 15M;
    }

The reason it is setup that way is because the SSL wildcard certificate for openfoodfacts.org is generated and kept on off1.

One thing we could do is to generate a robotoff.openfoodfacts.org certificate on dev, and then use the nginx from dev to send the queries to robotoff on port 5500.

**Comment by stephanegigandet** [comment]
It's possible that some of those errors were due to the dev server being slow: when products are edited, there is a notification sent to robotoff, and the server was waiting up to 180 seconds. It now waits only 2 seconds and return. See: https://github.com/openfoodfacts/openfoodfacts-server/issues/2849

**Comment by stephanegigandet** [comment]
It turns out robotoff was waiting for product opener which was waiting for robotoff which has only 2 threads.

So is this solved @raphael0202 ?

**Comment by raphael0202** [comment]
Yes it's solved, I've increased the worker number to 4 on Robotoff's side. Thanks!
