### ISSUE TITLE
Issue with the product count.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2834]
![image](https://user-images.githubusercontent.com/1689815/71884041-da151b00-3137-11ea-9061-8d6d14764715.png)

**Comment by hangy** [comment]
Can you explain the issue? Are we sure it's not the Android app?

**Comment by teolemon** [comment]
@hangy it was also visible in the web version
This seems to have been fixed during the night.

**Comment by stephanegigandet** [comment]
It's still in the app, I see it today, but I don't think it was on the web.

The issue is that the app makes a request to https://world.openfoodfacts.org/1.json to get the number of products each time it's launched. Which contributed to overloading the server when there is an app install spike. During one of those spikes (Envoyé Spécial), we made a static copy of the results so that nginx could serve it directly without having a product opener query + a mongodb query.


        location ~ ^/1.json$ {
                root /srv/off/html/static;
                try_files /1.json = 404;
        }


But that file has never been updated automatically:

-rw-r--r-- 1 root root 419717 May 21  2019 1.json

This is really something we need to change, it really doesn't make sense to download 420 kb of data just to get a product count. 

{"count":861761,"products":[{"ingredients_text_de":"Himbeere-Cranberry: Wasser,
geschälte _Sojabohnen_ (7,3%), Zucker, Früchte (6%)
...

I'm going to comment out the nginx code so that it does not serve a static copy for /1.json, but please file bugs for the iOS and Android app to retrieve the product count differently. Displaying a number with lots of digits like 1104919 may not be very useful anyway, we could just say "over 1 million products" and that would be much more powerful.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/75879575-e3f78980-5e1b-11ea-8b33-ef41caa2902f.png)
@stephanegigandet @hangy this problem also appears on the web. 
https://pt.openfoodfacts.org/

**Comment by stephanegigandet** [comment]
@teolemon @hangy : the problem in the image is unrelated to the original bug, so I opened a new one: https://github.com/openfoodfacts/openfoodfacts-server/issues/2991
