### ISSUE TITLE
Quality facet - Nutrition - list products where serving size can't be parsed

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#3029]
### What
Serving size has a specific goal: to let Open Food Facts app make a proportional calculation of each nutrient per serving size -- see: https://en.wiki.openfoodfacts.org/Data_fields

But dozens of "serving_size" values can't be parsed. Examples: `30 gr`, `2 liters`, `60`, `9 candies and 2 biscuits` and son on.

We should have a new quality facet to list each product where serving_size (and quantity?) has a value that can't be parsed.

### Part of 
- #5538

**Comment by stephanegigandet** [comment]
For quantity we have one: https://world.openfoodfacts.org/data-quality/quantity-not-recognized

**Comment by CharlesNepote** [comment]
> For quantity we have one: https://world.openfoodfacts.org/data-quality/quantity-not-recognized

Thanks. `14,342 products` on 2020-03-21.

Reminder for further investigation:
* [`normalize_quantity` function](https://github.com/openfoodfacts/openfoodfacts-server/blob/2f2bc53c748909b836791ab41722db6924357f8b/lib/ProductOpener/Food.pm#L3915) [only used for imports??? not used when users manually enter new products?]
* the [unit tests](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/t/food.t) for `normalize_quantity` function
* the [`quantity-not-recognized` facet code](https://github.com/openfoodfacts/openfoodfacts-server/blob/fe4908830c991e4b12bc035059d9afd843237b6f/lib/ProductOpener/DataQualityFood.pm#L910)

**Comment by benbenben2** [comment]
Is this still needed? 

Thanks to Mirabelle, now we have such list:

https://mirabelle.openfoodfacts.org/products?sql=SELECT+count%28*%29+AS+row_count%2C+serving_size%2C+serving_quantity+from+%5Ball%5D%0D%0AWHERE+serving_size+%21%3D+%22%22+AND+%28serving_quantity+IS+NULL+OR+serving_quantity+%3D+0.0%29+%0D%0AGROUP+BY+serving_size%2C+serving_quantity%0D%0A

**Comment by alexgarel** [comment]
@benbenben2 I think it's good to have it as a facet however.

**Comment by benbenben2** [comment]
@alexgarel @CharlesNepote @stephanegigandet 
For this Input:
![a1](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/a8d67b98-7e69-4ff0-b733-00274e77565b)
We get this:
![a2](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/7636d251-6ef1-4f18-9eb3-1e251a5ba7af)

Whereas for this input:
![b1](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/677b18e0-dc94-4509-8489-a50cd383a529)
We get this:
![b2](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/52446fb0-e108-4ed3-b7df-ae5154768e6c)
and this:
![b3](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/9162565a-215c-43fd-8ce2-aa048340bda0)




This " Nutrition data per serving - Serving quantity is 0 " facet, has been introduced by @stephanegigandet , before the creation of this current issue.




On the other hand, another example: https://world.openfoodfacts.org/product/3322680001236/12-crepes-de-landerneau-le-ster
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/d98cb6fa-2f63-4e2d-81ef-c64c38b04206)
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/110821832/523c48c2-eb3d-4914-b3c2-48a2255178d4)
**And there is not error regarding serving quantity.**


So, this is a little bit misleading because this error is raised when there is actually no serving quantity defined. And there is no error raised when serving quantity is 0.

What do you want to do there?
- rename error and include both cases: 0 and not defined, "serving quantity not recognized"
- have 2 separate errors (1 for 0 and 1 for not defined)
- something else
