### ISSUE TITLE
The new cropping experience breaks the Android app

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3051]
The new cropping experience breaks the Android app

![image](https://user-images.githubusercontent.com/1689815/76840163-02577f00-6837-11ea-9973-ed7f2523a2bb.png)

**Comment by Telperion87** [comment]
I also noticed this, which is preventing me to complete my last submissions. Also tried this on a couple devices for  3 or 4 different versions and I confirm that the cropping has something wrong on the app. To me it seemed to get the upper left corner of the picture, but from what OP posted, it seems otherwise.

**Comment by stephanegigandet** [comment]
@Telperion87 @teolemon . Thank you, it is now fixed.
