### ISSUE TITLE
Combine all UX images as a single sprite

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#325]
Combine all UX images as a single sprite to reduce queries and serverload

**Comment by hangy** [comment]
Just checked in Bitbucket. We have very few to none actual UI images that are specific to OFF/OBF. Most stuff probably comes from Foundation etc. Most images that are display in OFF/OBF are either product images or label logos, which are in SVG and should probably not be in sprites, because of their size. I think we should try to get SSL running for all domains and get HTTP2 running for that. If we do that for the static subdomain, that probably gains us more than any sprite images. (See this SO answer for [sprites and HTTP2](http://stackoverflow.com/a/32165576/11963))

Please reopen if you disagree. :)

**Comment by teolemon** [comment]
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/4671ab8c-b886-4da7-ae61-f9635164823b)
