### ISSUE TITLE
No way to see ingredient stats for multilingual countries

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3304]
![image](https://user-images.githubusercontent.com/1689815/79998089-8b0eae00-84ba-11ea-84a3-01745da61a93.png)
No way to see ingredient stats for multilingual countries especially when the language is only spoken in that country, like Catalan in Spain.

**Comment by stephanegigandet** [comment]
Well your screenshot is in fact the ingredients stats for Spain, for all products sold in Spain, regardless of their main language (Spanish, Catalan or otherwise).

If you want to see the numbers for products in Catalan only, you can do this:
https://es.openfoodfacts.org/idioma/catalan/idioma/en:1/ingredients?stats=1 (stats for products sold in Spain, with ingredients in Catalan, and with only Catalan)

Closing, please reopen if I didn't understand what you want.
