### ISSUE TITLE
Wikidata link malformatted

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#3399]
**Describe the bug**
The link to a wikidata entry on a category page is malformatted. It tries to go to https://www.wikidata.org/wiki/Https://en.wikipedia.org/wiki/Broth

Should it go to the wikidata or the wikipedia link,

**To Reproduce**
1. Go to https://world.openfoodfacts.org/category/broths
2. Click on the wikidata link
3. See error

**Expected behavior**
A nice wikipedia page.

**Comment by archanox** [comment]
https://world.openfoodfacts.org/category/radishes is also affected.
Currently is linking to [https://www.wikidata.org/wiki/Q7224565 # for the plant](https://www.wikidata.org/wiki/Q7224565%20#%20for%20the%20plant)
When it should just be [https://www.wikidata.org/wiki/Q7224565](https://www.wikidata.org/wiki/Q7224565)

Expected behaviour is actually "A nice wikidata page"
Broths is currently linking to [https://www.wikidata.org/wiki/https://en.wikipedia.org/wiki/Broth](https://www.wikidata.org/wiki/https://en.wikipedia.org/wiki/Broth) when it should be [https://www.wikidata.org/wiki/Q275068](https://www.wikidata.org/wiki/Q275068)
