### ISSUE TITLE
Quality facet - Nutrition - Flag products where 3 or more nutritional values are identical

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3554]
### What

- [ ] Flag products where 3 or more nutritional values are identical. This is a clear sign that someone entered bogus data.

https://dk-en.openfoodfacts.org/cgi/product.pl?type=edit&code=3760265420094

### Part of 
- #5538

**Comment by benbenben2** [comment]
Sharing some thoughts about this opened issue.


3 identical values is probably not enough because it is quite [easy to find](https://mirabelle.openfoodfacts.org/products?sql=--+SELECT+COUNT%28*%29+FROM+%5Ball%5D+--+275325%0D%0Aselect+fat_100g%2C+%22saturated-fat_100g%22%2C+carbohydrates_100g%2C+sugars_100g%2C+proteins_100g%2C+salt_100g%2C+sodium_100g%2C+code%2C+url+from+%5Ball%5D%0D%0A--+fat_100g+%3D%3D+%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+%3D%3D+sugars_100g+%3D%3D+proteins_100g+%3D%3D+salt_100g+%3D%3D+sodium_100g%0D%0AWHERE+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+sugars_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+sugars_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22proteins_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22proteins_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22salt_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AORDER+BY+CODE+DESC%0D%0ALIMIT+100) products with 3 identical values in the nutrition table and that are valid.

4 [seems also](https://mirabelle.openfoodfacts.org/products?sql=select+fat_100g%2C+%22saturated-fat_100g%22%2C+carbohydrates_100g%2C+sugars_100g%2C+proteins_100g%2C+salt_100g%2C+sodium_100g%2C+code%2C+url+from+%5Ball%5D%0D%0A--+fat_100g+%3D%3D+%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+%3D%3D+sugars_100g+%3D%3D+proteins_100g+%3D%3D+salt_100g+%28%3D%3D+sodium_100g%29%0D%0AWHERE+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+proteins_100g+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+proteins_100g+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+proteins_100g+AND+fat_100g+%3D%3D+salt_100g+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0A--+ORDER+BY+CODE+DESC%0D%0ALIMIT+10000
) not enough

Even [5 identical values]( https://mirabelle.openfoodfacts.org/products?sql=select+fat_100g%2C+%22saturated-fat_100g%22%2C+carbohydrates_100g%2C+sugars_100g%2C+fiber_100g%2C+proteins_100g%2C+salt_100g%2C+sodium_100g%2C+code%2C+url+from+%5Ball%5D%0D%0A--+fat_100g+%3D%3D+%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+%3D%3D+sugars_100g+%3D%3D+fiber_100g+%3D+proteins_100g+%3D%3D+salt_100g+%28%3D%3D+sodium_100g%29%0D%0AWHERE+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+fiber_100g+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+fiber_100g+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+fiber_100g+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+AND+%22saturated-fat_100g%22+%3D%3D+sugars_100g+AND+%22saturated-fat_100g%22+%3D%3D+fiber_100g+AND+%22saturated-fat_100g%22+%3D%3D+proteins_100g+AND+%22saturated-fat_100g%22+%3D%3D+salt_100g%29%0D%0AOR+%28%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+AND+%22saturated-fat_100g%22+%3D%3D+sugars_100g+AND+%22saturated-fat_100g%22+%3D%3D+fiber_100g+AND+%22saturated-fat_100g%22+%3D%3D+proteins_100g+AND+%22saturated-fat_100g%22+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28carbohydrates_100g+%3D%3D+sugars_100g+AND+carbohydrates_100g+%3D%3D+fiber_100g+AND+carbohydrates_100g+%3D%3D+proteins_100g+AND+carbohydrates_100g+%3D%3D+salt_100g+AND+carbohydrates_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0A%0D%0ALIMIT+10000) can be correct: 
 - https://world.openfoodfacts.org/product/0001200000005/aceite-coco






when almost all values are identical:
- it is often non food product (nb of identical values):
  - https://world.openfoodfacts.org/product/9787560276236/funda-de-movil
  - https://world.openfoodfacts.org/product/9788434237353/prueba
  - https://world.openfoodfacts.org/product/9788186004807/indian-cooking (6)
  - https://world.openfoodfacts.org/product/9788490494936/aaaaaa (5)
  - https://world.openfoodfacts.org/product/9788483469323 (6)
  - https://world.openfoodfacts.org/product/9788469834862/otro-mundo-a-la-vuelta-de-la-esquina-anaya (6)
  - https://world.openfoodfacts.org/product/9788467593396/cuaderno-de-expresion-plastica-sm (6)
- or it seems to be done by contributors when the product does not possess nutrition table:
  - https://world.openfoodfacts.org/product/9788175257665/test-green-fresh (6)
  - https://world.openfoodfacts.org/product/9788469628454/pan (6)
- it may be due to difficulty to extract data from the u.s./u.k. version of the nutritional fact (with 0%)

Maybe the alert could be set for **6 identical values**: fat_100g, saturated-fat_100g, carbohydrates_100g, sugars_100g, proteins_100g, salt_100g. 
Without fiber that is often missing and without sodium that can be either identical to salt or automatically converted from salt value. 
That would include [**~25 000 products**](https://mirabelle.openfoodfacts.org/products?sql=--+select+fat_100g%2C+%22saturated-fat_100g%22%2C+carbohydrates_100g%2C+sugars_100g%2C+fiber_100g%2C+proteins_100g%2C+salt_100g%2C+sodium_100g%2C+code%2C+url+from+%5Ball%5D%0D%0Aselect+count%28*%29+from+%5Ball%5D%0D%0AWHERE+fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g+AND+fat_100g+%3D%3D+sugars_100g+AND+fat_100g+%3D%3D+proteins_100g+AND+fat_100g+%3D%3D+salt_100g%0D%0A--+AND+salt_100g+%21%3D+sodium_100g%0D%0A--+LIMIT+10000)

**Comment by alexgarel** [comment]
@benbenben2 what about ignoring some typical values in this comparison ? (like 0, 0.5, 0.1, 1, 0.01) which are values typically found to mean "small enough".

**Comment by benbenben2** [comment]
Yes! Good point. 
That could make 2 different quality facets:
- 6 identical values (most of the time intentionally done, together with a non-food picture)
- 3 identical values + value is above 1 (to avoid 0.5 or 1 for "less than 0.5" or "less than 1"). [Some examples.](https://mirabelle.openfoodfacts.org/products?sql=--+SELECT+COUNT%28*%29+FROM+%5Ball%5D+--+275325%0D%0Aselect+fat_100g%2C+%22saturated-fat_100g%22%2C+carbohydrates_100g%2C+sugars_100g%2C+proteins_100g%2C+salt_100g%2C+sodium_100g%2C+code%2C+url+from+%5Ball%5D%0D%0A--+fat_100g+%3D%3D+%22saturated-fat_100g%22+%3D%3D+carbohydrates_100g+%3D%3D+sugars_100g+%3D%3D+proteins_100g+%3D%3D+salt_100g+%3D%3D+sodium_100g%0D%0AWHERE+%28%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+carbohydrates_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+sugars_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22saturated-fat_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+sugars_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22carbohydrates_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+proteins_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22sugars_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22proteins_100g%22+AND+fat_100g+%3D%3D+salt_100g%29%0D%0AOR+%28fat_100g+%3D%3D+%22proteins_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%0D%0A%0D%0AOR+%28fat_100g+%3D%3D+%22salt_100g%22+AND+fat_100g+%3D%3D+sodium_100g%29%29+AND+%0D%0Afat_100g+%3E+1%0D%0AORDER+BY+CODE+DESC%0D%0ALIMIT+100)
