### ISSUE TITLE
Implement function to delete user from Product Opener

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#3596]
As an admin, there is a checkbox on the interface to delete a user. However, the delete function has never been implemented. Users are currently deleted manually on the server.

<img width="912" alt="Capture d’écran 2020-06-11 à 10 49 06" src="https://user-images.githubusercontent.com/9609923/84370277-55439700-abd8-11ea-91b3-d2e6920e09d1.png">

**Comment by hangy** [comment]
> Users are currently deleted manually on the server.

Sounds like a bad idea, since that won't modify the change log. Maybe users should be renamed (#253) to something random, and have any personal information removed from their account instead? That way, we could still credit the products/changes to something else than a generic off-account for unknown changes.

**Comment by stephanegigandet** [comment]
@hangy : in fact we have a script to modify the change log, that we run before deleting users: https://github.com/openfoodfacts/openfoodfacts-server/blob/master/scripts/find_and_replace_user_id_in_products.pl

We could indeed rename the users with a random name and attribute the changes to them, that's a good idea. :)
