### ISSUE TITLE
Ingredients analysis: "[Ingredient processing method] + [ingredient 1] and [ingredient 2]" is not parsed

### ISSUE THREAD

**Issue by AcuarioCat** [openfoodfacts/openfoodfacts-server#3669]
Ingredients that are joined with  'y' or 'e' are not being separated and processed separately.
Examples:
concentrado de agua de coco y aroma natural
leche e yema de huevo

'y' and 'e' exist in the stopwords.

**Comment by stephanegigandet** [comment]
We currently parse ingredients that are joined with "y" (I will add "e").

But that works only when both ingredients are known (e.g. if we have "A y B", we separate them if and only if A and B are in the taxonomies, otherwise we risk to make false positives).

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=agua+de+coco+y+aroma+natural&type=add&action=process&.submit=Valider

**Comment by AcuarioCat** [comment]
Both ingredients are known and process individually, just not combined:

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=concentrado+de+agua+de+coco&type=add&action=process&.submit=Submit+Query

https://es.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=aroma+natural&type=add&action=process&.submit=Submit+Query

**Comment by AcuarioCat** [comment]
It seems the 'concentrada' is the cause of the combination failing

**Comment by stephanegigandet** [comment]
> It seems the 'concentrado' is the cause of the combination failing

That's right, we currently don't support the combination of ingredient processing + an "and".
