### ISSUE TITLE
Belgian home page link is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3679]
The link on `→ producten uit de mobiele app die verwerkt kunnen worden` is broken on the Belgian home page

**Comment by Ban3** [comment]
At least Finnish and Danish as well. Everywhere where the states are translated?

**Comment by hangy** [comment]
> At least Finnish and Danish as well. Everywhere where the states are translated?

German, too. The link at https://github.com/openfoodfacts/openfoodfacts-server/blob/f4774d12cf833c3a94b408e91f4561d767f851de/lang/de/texts/index.html#L31 doesn't match the link in production `https://de.openfoodfacts.org/status/to-be-completed` ➡️ What's actually deployed in production?

@stephanegigandet Could this be related to #3638? IIRC, the English tag names and values used to work in all international URLs, so that they didn't need to be translated (and bad translations in the HTML didn't break the links).

**Comment by stephanegigandet** [comment]
@hangy : good point. I think I'll add back English matching for all taxonomies, except ones we specifically don't want (e.g. ingredients on OFF).
