### ISSUE TITLE
Unknown Unicode nutrients are first saved, but deleted on the next save.

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#399]

**Comment by hangy** [comment]
Just tested this (admittedly, on my private test install) and I wasn't able to reproduce the problem. Did you change a specific nutrient or property of the product? (I changed the unknown nutrient's quantity; and in a different run the ingredient list, successfully).

**Comment by aleksejrs** [comment]
I changed nothing, just saved.

**Comment by aleksejrs** [comment]
IIRC, it happens also when I edit something else.

**Comment by aleksejrs** [comment]
Try nutrients with non-ASCII characters in names.

**Comment by hangy** [comment]
OK, looks to be related to some Unicode stuff. I had tried an Umlaut and that worked, but using '🤨' I was able to report your bug report. Thanks for hint. :+1:

**Comment by aleksejrs** [comment]
It happens with Cyrillics (like "элеутерозид").

In one case (issue #387), "Mg²⁺" was lost, but "HCO₃⁻" was not.

**Comment by hangy** [comment]
I think I have figured it out (not fixed, yet). When first entering an unknown nutrient, an id of `new_0` may be used in the form. When it is shown again in the editing dialog, then `nutriment_элеутерозид` will be used. For some reason, Perl/CGI does not seem to return that value when `param("nutriment_элеутерозид")` is called, so that the value gets deleted during the save.

**Comment by hangy** [comment]
I think I found an okay way to fix this in 035a5d09e93032d45e31c0ed856dd8d527c38dd9. A new pull request (private) was opened, so that @stephanegigandet can review the change.

**Comment by hangy** [comment]
Published to production.
