### ISSUE TITLE
docker/build_npm.sh requiring an old version of node.js

### ISSUE THREAD

**Issue by svensven** [openfoodfacts/openfoodfacts-server#4226]
Given node.js just had a [security update](https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/), I was wondering if docker/build_npm.sh needed the exact 12.16.1 version it's pulling in, or could just track the 12-alpine [tag](https://hub.docker.com/_/node) at least?

>docker run --rm -it -v node_modules:/mnt/node_modules -v $(cd .. && pwd)/:/mnt -w /mnt node:12.16.1-alpine npm install
>docker run --rm -it -v node_modules:/mnt/node_modules -v $(cd .. && pwd)/:/mnt -w /mnt node:12.16.1-alpine npm run build

Changing it to 12-alpine seems to work, although there's an extra line in the output, and I have no idea if it's significant:
> npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.

**Comment by hangy** [comment]
I don't think the mentioned CVEs actually affect out build, since most of them seem to be about Node.js being used as a server or otherwise process where something could be injected. Running it as our own build scripts should not be an issue, though.

That being said, we don't really *need* a specific version for that script, but I did try to keep the version in those scripts in sync with the one in https://github.com/openfoodfacts/openfoodfacts-server/blob/9d066685f2959cf15a38d30a1a10963d910e4a56/docker/frontend/Dockerfile#L1. If I remember correctly, a lot of guides recommend using very specific versions as base images, because lax tags might introduce breaking changes.

**Comment by svensven** [comment]
fair enough. i'm coming from the sysadmin angle of being religious about applying security updates. :) 

although it didn't occur to me to look at the dockerfile, i was looking at https://github.com/openfoodfacts/openfoodfacts-server/blob/9d066685f2959cf15a38d30a1a10963d910e4a56/.github/workflows/pull_request.yml and that says "12.x" for the node version. not sure if that's doing the same thing though.

**Comment by hangy** [comment]
> fair enough. i'm coming from the sysadmin angle of being religious about applying security updates. :) 

Oh, I totally understand and agree with that angle. We should update the used tag/version. The problem with using a `12` tag with Docker instead of `12.18.4` is that (without manually pulling the latest version before), the currently cached version will be used. If you have `12` locally with the image that was up-to-date with `12.16.2` then Docker will use that without trying to update the image first.

> although it didn't occur to me to look at the dockerfile, i was looking at https://github.com/openfoodfacts/openfoodfacts-server/blob/9d066685f2959cf15a38d30a1a10963d910e4a56/.github/workflows/pull_request.yml and that says "12.x" for the node version. not sure if that's doing the same thing though.

That's true. We could use the same exact version here. However, the node installer task actually starts with a clean slate and uses the most up-to-date version available.
