### ISSUE TITLE
Search criteria multiply themselves automatically

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4307]
Search criteria multiply themselves automatically. This should not happen ;-) 
https://world.openfoodfacts.org/cgi/search.pl?action=display&sort_by=unique_scans_n&page_size=20
![image](https://user-images.githubusercontent.com/1689815/95023900-ece55d80-067f-11eb-8648-857d9f57d0af.png)

**Comment by EmberCS15** [comment]
Hi @teolemon, I want to work on this

**Comment by EmberCS15** [comment]
I was going through how to reproduce the issue and let me lay down what I understood - 
* Naviagte to the URL in the Issue [Link](https://world.openfoodfacts.org/cgi/search.pl?action=display&sort_by=unique_scans_n&page_size=20)
* Under criteria select any make any selection
* Once the value of the selection is entered in the input box, it reproduces the criteria below. This specifically happens only when the input text is changed and the focus is removed from the input box after making some change in it.

I had a follow up question -
Initially, i.e, when the page renders, under the Criteria I see  2 selections available. Is this expected or due to the bug ?

**Comment by teolemon** [comment]
Yes. And as you fill them, more should appear as needed, but not prefilled, and not like this

**Comment by stephanegigandet** [comment]
Related code:

https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/js/search.js

https://github.com/openfoodfacts/openfoodfacts-server/blob/master/templates/search_form.tt.html
