### ISSUE TITLE
US presentation of nutritional values incorrect.

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#4377]
**Describe the bug**
Some field must be in %DV and B12 is missing.

**To Reproduce**
See https://us.openfoodfacts.org/product/0810934030192/just-like-cream-cheese-original-violife

**Screenshots**

**Comment by aleene** [comment]
![image](https://user-images.githubusercontent.com/1329905/96375264-289c1f00-1178-11eb-8122-74135bce31c0.jpeg)

**Comment by svensven** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/5736616/96387907-72e3c700-119d-11eb-8b57-6d1fee7c0a50.png)

**Comment by stephanegigandet** [comment]
@svensven : the issue is about the default fields shown when we add a US product. You can reproduce it by adding a new product on https://us.openfoodfacts.org

![image](https://user-images.githubusercontent.com/8158668/96416851-dcd98c00-11f0-11eb-8bcf-789537a23898.png)


@aleene : which fields should have a different unit and are there other fields missing in the new US tables?

**Comment by aleene** [comment]
Potassium should be in %DV

**Comment by aleene** [comment]
Vitamin D should be in %DV

**Comment by aleene** [comment]
Vitamin B12 should be added.

**Comment by stephanegigandet** [comment]
https://www.fda.gov/food/food-labeling-nutrition/changes-nutrition-facts-label

For vitamins / minerals: the new labels also have values in g / mg / mcg in addition to %DV. We should add them in those units other than %DV, as the FDA change those DV.

So in fact we do have the right nutrients for the current FDA nutrition facts, but we should switch Calcium and Potassium to mg.

**Comment by stephanegigandet** [comment]
![image](https://user-images.githubusercontent.com/8158668/97075080-851c9580-15e1-11eb-8dc8-f365bb7a3281.png)
