### ISSUE TITLE
Return image_packaging_url in API

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4442]
Similar to [image_front|ingredients|nutrition]_url

**Comment by SaifurRahmanMohsin** [comment]
Does it take a while to reflect [in production](https://ssl-api.openfoodfacts.org/api/v0/product/8901063017252.json?fields=origins,other_information,link,packaging,packaging_url,ingredients_that_may_be_from_palm_oil_tags,product_name_en,image_nutrition_url,image_packaging_url,generic_name_en,traces,vitamins_tags,states_tags,nutrition_data_per,ingredients_analysis_tags,purchase_places,ingredients,recycling_instructions_to_recycle,product_name,ingredients_text,warning_en,generic_name,customer_service,ingredients_from_palm_oil_tags,image_front_url_en,ingredients_from_or_that_may_be_from_palm_oil_n,amino_acids_tags,countries,conservation_conditions_en,lang,customer_service_en,recycling_instructions_to_discard_en,stores,allergens,languages_codes,nova_groups,brands,conservation_conditions,serving_size,traces_tags,recycling_instructions_to_discard,last_modified_by,code,quantity,no_nutrition_data,image_small_url,ingredients_text_en,creator,additives_tags,manufacturing_places,other,other_nutritional_substances_tags,image_nutrition_url_en,image_packaging_url_en,nutrition_grades_tags,recycling_instructions_to_recycle_en,cities_tags,nutriments,url,selected_images,editors_tags,allergens_hierarchy,minerals_tags,brands_tags,last_modified_t,image_front_url,labels_hierarchy,emb_codes_tags,warning,allergens_tags,image_ingredients_url_en,environment_impact_level_tags,nutrient_levels,image_url,created_t,environment_infocard,nutrition_grade_fr,ingredients_from_palm_oil_n,other_information_en,countries_tags,image_ingredients_url,categories_tags,labels_tags)?

**Comment by aleene** [comment]
You can find the packaging image under images, which is sufficient info.

**Comment by SaifurRahmanMohsin** [comment]
@aleene As you mentioned in [an earlier comment](https://github.com/openfoodfacts/openfoodfacts-server/issues/4442#issuecomment-719696496), adding packaging to `selected_images` would have been ideal and would enable me to directly get the normal size image from the array and use it [like this](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java#L199-L206). However, now I've had to introduce images array field into the product details fetch request in order to achieve the same in [my latest commit](https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3565/commits/b44b0fbf5843d0c00927c336f056d240d28e8a8b) to PR openfoodfacts/openfoodfacts-androidapp#3565

**Comment by aleene** [comment]
That is what I did as well. Now you can get rid of all selected_images.
