### ISSUE TITLE
Adding "% DV" of some nutrients causes an error

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#450]
Try adding any of these nutrients with "% DV" as the unit:
- riboflavin
- niacin
- Vitamin B3

An error page appears (example):

> Attempt to access disallowed key 'riboflavin' in a restricted hash at /home/off-fr/cgi/product.pl line 450.

**Comment by TaciteOFF** [comment]
Temporary fix : 
When you start typing "niacin", you should have a tooltip to select "Vitamin B3 / Vitamin PP (Niacin)".
If you select it and add the %DV value, you will have no problem

**Comment by aleksejrs** [comment]
Issue #451.  If I switch to from `ru.` to `ru-en.`, I get autocompletion of English text.

**Comment by TaciteOFF** [comment]
Nutrients have to be translated here : 

http://en.wiki.openfoodfacts.org/Translations_-_Names_of_nutrients

**Comment by aleksejrs** [comment]
Again, "Attempt to access disallowed key 'vitamin-c-ascorbic-acid' in a restricted hash at /home/off/cgi/product.pl line 498."

It lost all my textual input!

**Comment by teolemon** [comment]
Vitamin C related bug, @stephanegigandet

**Comment by hangy** [comment]
OFF tries to calculate the value from `$Nutriments{$nid}{dv}` and `$Nutriments{$nid}{iu}`, so that %DV and IU result in some g value, I guess. For unknown nutrients this probabyl fails, because `$Nutriments{$nid}` will be unknown.

https://github.com/openfoodfacts/openfoodfacts-server/blob/6f6700f548915a5c71bd8a80f88538529b4795f9/cgi/product_multilingual.pl#L495-L502

I'm going to limit this to be run only if `$Nutriments{$nid}` is known. We cannot calculate a useful value for any other case anyways.
