### ISSUE TITLE
Add relation language and languageCode in api

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#462]
Current version of the world read api has multiple fields related to the language. (languages_hierarchy, languages, languages_codes, languages_codes, languages_tags). Not sure why these are all needed in the api.

For my app only one things is noted: I must know which languages are contained in the product. I use the languages_hierarchy-field for that. Then I must derive the language_codes corresponding to these languages in order to build the relevant language dependent keys, such as "ingredients_text_nl". In order to do this I need a data-list, which maps these two (language and language_code).

It would be nice to have this mapping in the api as well. (or implement the language dependent keys differently).

This would do it for me:
"languages":[{"lang":"en:spanish","code":"es"},{"lang":"en:dutch","code":"nl"},{"lang":"en:french","code":"fr"}]

**Comment by aleene** [comment]
Maybe it is better to do it like a dictionary:
"languages":["en":"en:english","pt":"en:portuguese","fr":"en:french"]

**Comment by niwrA** [comment]
I really love the api (just that it is there, its simplicity, its speed and how fast it represents something I've scanned in with the phone App. Really good stuff).

However, the ingredients I would like to see linked to a language independent entity. Most ingredient names are fixed in all languages so some kind of automatic process should be able to help out here. This would make the data much more powerful, in that you could calculate all sorts of labels from them (vegan, vegetarian, etc.). Even when people add such labels manually, the tags can be unreliable and then the ingredient list can at least be some kind of checksum. Look forward to the code for the project to become public so we can contribute!

**Comment by aleene** [comment]
In order to be able to this an ingredients taxonomy must be created. Difficult and a lot of work.

The code is public, the taxonomies are public, so you can contribute.

**Comment by aleene** [comment]
too old
