### ISSUE TITLE
Search for "Tarchun" does not find the product

### ISSUE THREAD

**Issue by aleksejrs** [openfoodfacts/openfoodfacts-server#466]
### What
- http://world.openfoodfacts.org/cgi/search.pl?search_terms=tarchun&search_simple=1&action=process
- http://world.openfoodfacts.org/cgi/search.pl?search_terms=Tarchun&search_simple=1&action=process

These should find http://world.openfoodfacts.org/product/4038745603527/tarchun , but they don't.

### Part of
- #5492

**Comment by hangy** [comment]
The executed MongoDB query `{ '_keywords': { '$all': ['tarchun'] } }` does not return the value either. One reason could be that the `product_name` is empty, see [API](https://world.openfoodfacts.org/api/v1/product/4038745603527.json), and thus they `_keywords` property does not contain the value.

```
> db.products.find({'code': '4038745603527'}, {'_keywords': 1});
{ "_id" : "4038745603527", "_keywords" : [ "тархун", "limonaden" ] }
```

The multilingual names are not indexed by [`index_product`](https://github.com/openfoodfacts/openfoodfacts-server/blob/65dfc9842e9c579985867ae3073cda1766003f63/lib/ProductOpener/Products.pm#L909-L930), so that kinda explains that, I guess. Maybe we need keywords for each language of the product to be indexed separately, ie. `_keywords_de`, `_keywords_ru`, etc.? However, this sounds like it could be bad to index with MongoDB …

**Comment by aleksejrs** [comment]
So this is #235.

**Comment by teolemon** [comment]
but still present

**Comment by raphael0202** [comment]
Issue is resolved using Search-a-licious: https://search.openfoodfacts.org/?q=Tarchun
As we're migrating to search-a-licious, I'm closing the issue.
