### ISSUE TITLE
Update some SVG images / icons to make the viewport match the width and height

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#4674]
The viewport of some SVG icons like the Nutri-Score, NOVA and Eco-Score icons does not match the width and height. It should be perfectly fine, but in practice at least one SVG renderer (the flutter_svg package in Flutter) does not handle it and clips the image.

![image](https://user-images.githubusercontent.com/8158668/103180959-9f057d80-489b-11eb-83a7-880f002cc2f8.png)

The easiest workaround is probably to just update the SVG images to change the viewport so that it matches the width and height.

e.g. current values for the Nutri-Score icons:

````````
   width="240"
   height="130"
   viewBox="0 0 744.09449 1052.3622"

**Comment by monsieurtanuki** [comment]
@stephanegigandet From what I read [here about the svg `viewbox`](https://css-tricks.com/scale-svg/), it's not only about dimensions but also cropping. And I don't see how `viewBox="0 0 744.09449 1052.3622"` could mean something different from "it's higher than wide", which was the displayed result in flutter.

I don't know if there's a bug in flutter_svg, or if flutter_svg has a less lenient behavior.

The point is that we should find a process so that svg files are checked against a set of rules when they are made available to the public, one being possibly "check width/height match the viewbox dimensions" (or something like that).
