### ISSUE TITLE
Producer Platform - Allow for getting a list of all users on a domain

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5042]
### What
- [ ] Allow for getting a list of all users on a domain to see who we can attach to an organisation
- [ ] https://world.openfoodfacts.org/cgi/user.pl?type=view&userid=*@my-super-food-company.com

### Part of
- #5521

**Comment by hangy** [comment]
Is that really an option we need regularly? Maybe a simple script with direct access to the users directory would be enough. If this was an API, it would necessarily need to be a super-admin option for data privacy issues, because searching for all users that use a specific email domain could be a massive GDPR issue.

**Comment by teolemon** [comment]
yup, I guess a grep server side can suffice. I think admins might need regularly to defragment producer account (eg people from a company who separately create accounts).
Eventually, proposing automatically to request to join Coca-Cola if you have @coca-cola.com might be a better solution

**Comment by manon-corneille** [comment]
Fixed by this https://github.com/openfoodfacts/openfoodfacts-server/issues/6978
