### ISSUE TITLE
"Création du produit" in French in History log

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#515]
http://ru.preprod.openfoodfacts.org/cgi/product.pl?type=edit&code=4690228009297

![image](https://cloud.githubusercontent.com/assets/1689815/19352598/a9b190b2-9160-11e6-8064-24ef4d716cc7.png)

**Comment by hangy** [comment]
Hard coded string at https://github.com/openfoodfacts/openfoodfacts-server/blob/5b43a3584b7843716870e2c349c6dc136bcef37f/cgi/product_multilingual.pl#L128. But what should it be? Just switch it up to English or should a translatable string be added? I think keeping it in one language could be useful, because of multilingual products.

**Comment by teolemon** [comment]
Hard coded in English and decode on the fly to the locale ?
Something pregenerated like taxonomies for performance ?
