### ISSUE TITLE
Limit percent max of some ingredients (e.g. aroma, ferments) (needed for milk estimate for Nutri-Score)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#5369]
### What
We currently estimate % min and max for each ingredient in the ingredient list. And those % can be used for the Nutri-Score (e.g. to see if a product has more than 80% milk and should not be considered a beverage), for the Eco-Score etc.

For something like "Milk, ferments", we get this result:
https://world.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Milk%2C+ferments&type=add&action=process&submit=Envoyer

Milk -> en:milk - vegan: no - vegetarian: yes - percent_min: 50 - percent_max: 100
ferments -> en:ferment - vegan: maybe - vegetarian: maybe - percent_min: 0 - percent_max: 50

In practice, we could consider that some ingredients are never above 5% (unless they are the first and sole ingredients, like a bottle of ferments or a bottle of aroma).

And in this case, we could determine that this product is at least 95% milk, instead of at least 50% milk.

### Part of
- #5517 
- #5706

**Comment by john-gom** [comment]
I'm working on this at the moment. Proposing to add a percent_max:en property to the ingredients taxonomy.

**Comment by john-gom** [comment]
In order to limit the "blast radius" of this change the percent_max will not be applied in the following scenarios:

- To sub-ingredients
- Where the first ingredient has a percent_max defined (e.g. the product is entirely flavouring)
- If the percent_max would be less than any later (smaller quantity) ingredients
- If the larger ingredients have percentages specified and the percent max when added this would not allow the total to reach 100%
