### ISSUE TITLE
Taiwan support

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#5419]
**Describe the bug**
The page for Taiwan is now a mix of simplified and traditional script.
![image](https://user-images.githubusercontent.com/1329905/127336533-889e2e4d-dcf1-4793-9a69-f5d26e1303cd.png)

For a start I do not see a zh_TW.po file. Can I create one?

**Comment by hangy** [comment]
> For a start I do not see a zh_TW.po file. Can I create one?

It does exist: https://github.com/openfoodfacts/openfoodfacts-server/blob/cf44b8911d863e4a0b0305f927dc68823dbde0d3/po/common/zh_TW.po

Generally, new `po` files shouldn't be added manually. They should be added to [crowdin.yml](https://github.com/openfoodfacts/openfoodfacts-server/blob/6c881b3fb0ad1dcee354633c697d0a04a5131154/crowdin.yml), so that they can be translated through [Crowdin](https://translate.openfoodfacts.org). I believe [zh-TW](https://translate.openfoodfacts.org/project/openfoodfacts/zh-TW) should be the correct starting point for you. Thanks for any contributions. 🙂

**Comment by aleene** [comment]
I guess I was looking for a translation that was not there yet, and so missed the file.
