### ISSUE TITLE
Ingredients empty if ingredient text empty for main language

### ISSUE THREAD

**Issue by zond** [openfoodfacts/openfoodfacts-server#5546]
### What
I refer to our conversation in Slack (https://openfoodfacts.slack.com/archives/C0289KSGR3K/p1629800910053500).

TL;DR

If the ingredient text for the main language is empty, the ingredient list will be empty too - even if other languages have ingredient texts. Me an @CharlesNepote at least agreed that it was reasonable to take some other language in that case.

### Part of
- #5706

**Comment by raphael0202** [comment]
@alexgarel we discussed this a few weeks ago, but there is actually already an issue filled on Github for this ;)
I think as well that the current approach is confusing to users, as they have to change the main language for ingredient analysis to be performed.

I would suggest:
- to parse ingredient list in product main language first if available, otherwise check other available languages.
- add a new `ingredients_lc` field in MongoDB (and sto files) that store the language code that was used to parse ingredient list.
- display on product page (in ingredient analysis panel) and product edit page the language that was used to parse the ingredient list.

This would also make implementation of automatic ingredient extraction by Robotoff easier, as we wouldn't have to switch product main language for ingredient parsing to be done (and @stephanegigandet was anyway not in favor of changing the main language, as it is supposed to be the most visible language on the packaging).

**Comment by raphael0202** [comment]
Done by #8855.
