### ISSUE TITLE
Password reset capitalization

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-server#5807]
### Describe the bug

If you want to reset your password but enter the email with the wrong capitalization, it says "There is no account with this email".

### To Reproduce

Try [requesting a password reset email](https://world.openfoodfacts.org/cgi/reset_password.pl), but make the first letter uppercase (or lowercase)

### Expected behavior

The capitalization should be ignored

### Type of device

Browser (Firefox)

**Comment by alexgarel** [comment]
I'll give it a try as a first bug.

**Comment by alexgarel** [comment]
Huuuum, in fact we never apply transformations on email addresses, so that ain't so easy. 

I checked in prod, we have something like 10215 out of 110262 users which registered with an email with a capital letter inside.

What I propose:

1. I will implement a fix that will work on most case: if the email is not found as is, try with lower cased email
2. We should open up a new bug to understand if we want to always lowercase email addresses in our database (or at least in user_emails.sto ?). That could be only for new registrations.

@stephanegigandet any though on second point ?

**Comment by stephanegigandet** [comment]
Thanks @alexgarel. I think it would make a lot of sense to lowercase all emails in user_emails.sto (existing and new) so that we solve the issue for emails for uppercase, and not only for password reset, but also for logging in. So the approaches you suggest sound good to me.

**Comment by M123-dev** [comment]
@alexgarel. just tried it again and it still does not work as expected, from what I can take out of https://github.com/openfoodfacts/openfoodfacts-server/commit/527e31760e47d240a85ffb0e48e4bb74d0754b9c 

`$id = lc $id;`

it only makes the provided one lowercase not the saved one. Mine is saved with a capital M at the beginning
