### ISSUE TITLE
`make tests` is failing

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-server#6148]
### Describe the bug

`make tests` is failing both on local and on CI.

### To Reproduce

Clone the repo.
Run `make tests`

### Expected behavior

Tests should pass

### Type of device

REST-API

**Comment by alexgarel** [comment]
@stephanegigandet  indicates that this is because we need to rebuild changed taxonomies before running tests.

Currently the script is in js, and we don't have Node in the docker (and don't want it), so we may rewrite this in perl (this would also be more consistent). We can use something like https://metacpan.org/pod/Parallel::Batch
