### ISSUE TITLE
Adding HTTPS certificate to the Preprod server ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#645]
On Chrome Canary, it's not possible to connect in HTTP to the preprod server to test translations. It somehow redirects to HTTPS with no opt-out (no way to indicate the website as safe)
Consider having secured versions for a limited number of domains ?

**Comment by hangy** [comment]
> It somehow redirects to HTTPS with no opt-out (no way to indicate the website as safe)

I'm pretty sure that's because of the [HSTS](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet) header `Strict-Transport-Security:max-age=63072000; includeSubdomains`.

> Consider having secured versions for a limited number of domains ?

Guess having a Let's Encrypt certificate for some subdomains cannot hurt, but a paid one would be overkill. Unfortunately, wildcard certs are only valid for one level (openfoodfacts.org and *.openfoodfacts.org), so that the main domain one's cannot be used for *.preprod.openfoodfacts.org.

**Comment by stephanegigandet** [comment]
I added a letsencrypt certificate for the top 100 subdomains on preprod.
