### ISSUE TITLE
Import 12000 Swiss products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#649]
- JSON format and images.
- Link between product data and images are within the JSON
- 3 languages
- 14000 products
- Files already on the server

**Comment by teolemon** [comment]
I'm getting new products in a separate folder.

**Comment by hangy** [comment]
Note that the build [failed](https://travis-ci.org/openfoodfacts/openfoodfacts-server/builds/199302318):
```
t/perlcritic.t ... 55/? 
#   Failed test 'Test::Perl::Critic for "scripts/import_openfood_ch.pl"'
#   at /home/travis/perl5/lib/perl5/Test/Perl/Critic.pm line 104.
# 
#   I/O layer ":utf8" used at line 8, column 1.  Use ":encoding(UTF-8)" to get strict validation.  (Severity: 5)
t/perlcritic.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/198 subtests 
```

**Comment by teolemon** [comment]
Closing ?

**Comment by stephanegigandet** [comment]
From @teolemon : we are missing the German/Italian/English variants for product names:

https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=7617067012841
https://www.openfood.ch/fr/products/12549

I didn't notice the "name" field was translated. We can make a new pass to only update the product_name field for those languages, for the products where it is available.

**Comment by stephanegigandet** [comment]
So the issue is that I use the "name" field to set the product_name_fr, without using the name-translations values.

I'm working on a new script to add the product_name_[de|ìt|en|fr] values from the name-translations field. The fr value has already been set by the first pass. I will overwrite it with the french value from name-translations if the current value is the german / italian / english value.

This is what we had in the json file we imported:

{"data":{"id":"15675","type":"products","attributes":{"name":"Coop : Qualité\u0026Prix : Baumnüsse aus Grenoble getrocknet","name-translations":{"de":"Coop : Qualité\u0026Prix : Baumnüsse aus Grenoble getrocknet","fr":"Coop : Qualité\u0026Prix : Noix de Grenoble sèches","it":"Coop : Qualité\u0026Prix : Country : Noci di Grenoble secche"},"barcode":"7610800927082",

the "name" was set with the German translation, but now it is set to French on https://www.openfood.ch/api/v1/products/15675.json

**Comment by stephanegigandet** [comment]
Products updated in production.

8628 edited products
8628 editions
field product_name_de - 6270 editions
field product_name_en - 2126 editions
field product_name_fr - 4400 editions
field product_name_it - 4657 editions
