### ISSUE TITLE
Barcodes stored as numbers instead of strings in Excel and CSV exports

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6782]
### Describe the bug

Barcodes with leading 0s have the leading 0s removed in CSV and XSLX exports.

### To Reproduce

Export some products from the search results page.

### Expected behavior

Leading 0s should be kept.

### Type of device

Other

**Comment by benbenben2** [comment]
Hello!
Being new on OFF and on Perl, I was a bit too optimistic when I thought I could work on this issue all by myself -_-'

Instead, I will share some comments. 
If you have time you can guide me and maybe I could try to work further on it but it will take me some time, definitely.

This issue can be reproduced as follows:
- go to https://world.openfoodfacts.org/
- click on "Advanced search"
- search for "Coconut original coconutmilk - silk" (or "Tulu Drinks - Strawberry Flavor", for another example)
- download either XLSX or CSV

**Comments:** I think that changes have to be made in lib/ProductOpener/Export.pm and that a solution could be to 1. add a variable to fetch the information of how many digits compose the code (the first element of the list in "codes_tags" in $product_ref could be used maybe) and 2. put a new condition "if ($field eq "code") {" etc. Not sure extacly where it should be put (line 325 maybe?). 

- I am not totally sure that this solution will work acutally, because I am not sure that it will end up as string or as integer at the end.
- Is there a way to run some parts of the code locally for testing?
- I don't understand why in the output file there are tags of some fields that are defined in Config_off.pm (like brands, countries) - while brands_tags and countries_tags themselves are **not** in Config_off.pm. Whereas, on the other hand, tags of code are not in the output file while code is defined in Config_off.pm. Is it because it is codeS_tags (plural)? 
- I also don't get the part "defined $tags_fields{$field})/(defined $language_fields{$field}" (altough I can see the result in the output file), what is $tags_fields and $language_fields, I don't see them defined in other files?
