### ISSUE TITLE
Make target for running a single test

### ISSUE THREAD

**Issue by yuktea** [openfoodfacts/openfoodfacts-server#6876]
Story: As a developer working on OpenFoodFacts, I need to run tests often to verify I'm not breaking anything or the tests I'm writing pass. Running the full test suite takes time and is not necessary in most circumstances. On the other hand, I do not have a dedicated Make target to run single tests. Resolution: add a Make target to run tests from a single file. This will enhance both the developer experience and potentially developer productivity.

**Comment by alexgarel** [comment]
@yuktea the problem is Make does not support arguments.

We use Make because it is quite ubiquitous but it's not really the best tool for the job.

One alternative I see would be to keep the Make but also have a shell command of our own where we add some shortcuts. This would leave far more room to creativity.
The problem I see is that there is not sh on windows, but I think git on windows comes with a shell, I'm not sure if it's a full capable shell or not.

**Comment by alexgarel** [comment]
Ah ah didn't see the PR, very cool. so my comment is indeed ko ;-)
