### ISSUE TITLE
First state filter ignored in drilldown

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#70]
I just tried filtering products by states to get those that have a valdiated photo and no nutrition facts: [Photos validated & nutrition facts to be completed](http://de-en.openfoodfacts.org/state/photos-validated/state/nutrition-facts-to-be-completed). The first filter for "photos validated" is ignored and only "nutrition facts to be completed" is applied. I would have expected to see the same items as with [the search](http://de-en.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=states&tag_contains_0=contains&tag_0=Photos%20validated&tagtype_1=states&tag_contains_1=contains&tag_1=Nutrition%20facts%20to%20be%20completed&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&action=display).

**Comment by stephanegigandet** [comment]
It's a more global issue: queries in MongoDB are expressed has a hash of key / value pairs. Which means there can be only one condition for one field (like in your case states).

There is a special $and syntax that enables to have lists of conditions (which is used in the search form conditions) but it was not used for the URLs conditions.

The worse was in urls like http://de-en.openfoodfacts.org/country/spain/country/france where we want products that have 3 values for the country field.

Fixed with $and syntax.

**Comment by stephanegigandet** [comment]
Updated query for the url above:

Display.pm - search_and_display_products - query:
$VAR1 = {
          'countries_tags' => 'en:germany',
          '$and' => [
                      {
                        'states_tags' => 'en:photos-validated'
                      },
                      {
                        'states_tags' => 'en:nutrition-facts-to-be-completed'
                      }
                    ]
        };
