### ISSUE TITLE
Raw seeds of flax, chia, hemp, etc* do not seem to be considered as "fruits, nuts, seeds" 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#7075]
From a user report: "Bogue du moteur de calcul Nutriscore ? Les *graines crues de lin, chia, chanvre, etc*. riches en oméga 3 ne semblent pas considérées comme des "fruits, noix, graines" par le moteur de calcul nutriscore. Elles obtiennent tjs une note 0 pour "fruits, noix, graines"."

Nutriscore calculation engine bug? *Raw seeds of flax, chia, hemp, etc*. rich in omega 3 do not seem to be considered as "fruits, nuts, seeds" by the nutriscore calculation engine. They always get a score of 0 for "fruits, nuts, seeds".

**Comment by stephanegigandet** [comment]
It's not "fruits, nuts, seeds", it's "fruits, vegetables, nuts".

The Nutri-Score spec specifically excludes them:

Chia, poppy,sunflower, flax seeds and pine nuts that belong to Eurocode group 7.30 not covered by the
FSA document. 

From the Nutriscore spec https://www.santepubliquefrance.fr/content/download/150263/file/QR_scientifique%20et%20technique_EN_310322.pdf :

"1. DEFINING FRUITS, VEGETABLES, PULSES AND NUTS AND RAPESEED, WALNUT AND OLIVE OILS
The Eurocode 2 classification4
(in English) defines the food groups. Under this system ‘Fruits’ are defined as
products in Group 9, ‘Vegetables’ as products in Group 8, 'Pulses' as products in Group 7.10, 'Nuts' as
products in Groups 7.20 and 7.40. The groups are defined according to this classification:
i. Group 7.10 (Pulses);

3 accessed from
https://www.researchgate.net/publication/267194254_Application_of_the_Nutrient_profiling_model_Definition_of
_'fruit_vegetables_and_nuts'_and_guidance_on_quantifying_the_fruit_vegetable_and_nut_content_of_a_processe
d_product
4accessed from
http://www.danfood.info/eurocode/
21
ii.Group 8.10 (Leaf vegetables); 8.15 (Brassicas); 8.20 (Stalk vegetables); 8.25 (Shoot vegetables); 8.30
(Onion-family vegetables); 8.38 (Root vegetables); 8.40 (Fruit vegetables); 8.45 (Seed vegetables and
immature pulses); 8.50 (Edible fungi); 8.55 (Seaweeds and algae); 8.60 (Vegetable mixtures)
iii Group 9.10 (Malaceous fruit); 9.20 (Prunus species fruit); 9.25 (Other stone fruit); 9.30 (Berries); 9.40
(Citrus fruit); 9.50 (Miscellaneous fruit); 9.60 (Fruit mixtures).
iv Group 7.20 (underground pulses); 7.40 (nuts)
The list of the various foods in these groups is available in appendix 3.
Herbs listed in group 12.20 of the Eurocode 2 classification, are also included in the component as well as
olive, walnut and rapeseed oil.
Clarifications:
- Coconut presents particular issues because it is eaten in a different way to other nuts.
Depending on how it is eaten, it can be included in the following groups:
- fresh coconut flesh should be scored as fruit
- the water of the coconut (or “coconut water”, defined as the liquid extracted from the centre of the
unripe green coconut, without extracting or pressing the coconut flesh) should be scored as beverage. The
coconut water can be counted as fruit (when it is sold as such or used as an ingredient).
- the coconut milk (obtained by extracting or squeezing the coconut flesh of a ripe coconut) should be
scored as food. Ingredients coming from coconut (e.g. coconut extract) can be considered as fruit. However,
any additional water should not be taken into account.
- the coconut cream should be scored as added fat. Ingredients coming from coconut (e.g. coconut extract)
can be considered as fruit. However, any additional water should not be taken into account.
- desiccated and dried coconut are equivalent to dried fruit. Dried shredded coconut is considered as dried
fruit.
- coconut which is processed beyond the original product should not be included.
 Pickles are a variety of CUCUMIS SATIVUS, like cucumber. In light of the botanical name, they are
listed as vegetables.
 Capers are not listed, they are not included in vegetable calculations.
The following are not counted:
 Tubers, particularly potatoes and other starchy vegetables (such as yams or manioc from Group 8.34)
are excluded from the calculations.
 Pulse and maize flours are not counted for the fruit and vegetables calculations either.
 Quinoa, the nutritional composition of which is similar to that of cereals, is not considered a vegetable.
 Spices: do not belong to generic Eurocode group 8 (which contains vegetables), but to group 4 instead. 
22
**Chia, poppy,sunflower, flax seeds and pine nuts that belong to Eurocode group 7.30 not covered by the
FSA document.**
 Other foods that do not belong to Eurocode groups 9, 8, 7.10, 7.20, 7.40 and 12.20."
