### ISSUE TITLE
Parsing bug for .po files with brackets [ ] - breaks products evolution graphs

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#771]
This breaks the javascript for the product evolution graphs.

It seems to be a bug in the parsing module, I added a test in it:

```
#   Failed test 'months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']'
#   at t/10-parse.t line 59.
#          got: '~['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'~]'
#     expected: '['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']'
# Looks like you failed 4 tests of 25.

```

**Comment by maddingue** [comment]
Hello Stéphane,

JavaScript structure in `.po` strings? You're letting the old demons come back ;)

This behaviour is actually caused by the transformation of the gettext syntax to the maketext syntax, as documented in [Locale::Maketext](https://metacpan.org/pod/Locale::Maketext#BRACKET-NOTATION). Given this won't be used in the context of ProductOpener, I've added an option `disable_maketext_conversion` which will do exactly what it means: avoid translating to maketext syntax. This will have the added bonus to make your use case a tiny bit faster.

[Locale::Maketext::Lexicon::Getcontext 0.05](https://metacpan.org/release/SAPER/Locale-Maketext-Lexicon-Getcontext-0.05) is on its way to the CPAN.

You'll simply need to edit [ProductOpener::I18N](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lib/ProductOpener/I18N.pm#L21) and change the `use Locale::Maketext::Lexicon` line this way:
```perl
use Locale::Maketext::Lexicon _auto => 0, _decode => 1, _style => "gettext",
        _disable_maketext_conversion => 1;
```
(I know I can make this change myself, but I'm unsure on which branch you'd prefer it to be.)
You can already apply this change, as unknown options are ignored and do not generate errors.

**Comment by teolemon** [comment]
@stephanegigandet ready for deployment. Probably useful for the conversation about European extension we're going to have.
