### ISSUE TITLE
Energy-value-in-kcal-does-not-match-value-computed-from-other-nutrients: exclude more products

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7789]
### Describe the bug

In the Wikipedia article about [Food Energy](https://en.wikipedia.org/wiki/Food_energy), we can read: "_Some polyols, like [erythritol](https://en.wikipedia.org/wiki/Erythritol), are not digested and should be excluded from the count_".

For example, stevia sugars generally contain 90+g/100g of polyols and those are erythritol.
1000+ sweeteners are concerned, mainly stevia or 0 calories sugars: https://world.openfoodfacts.org/data-quality-error/energy-value-in-kcal-does-not-match-value-computed-from-other-nutrients/category/sweeteners

Calorie-free ingredients:
* erythritol (E968) (0.2 Kcal/g): https://en.wikipedia.org/wiki/Erythritol
* stevia (natural): https://en.wikipedia.org/wiki/Stevia
* acesulfame K (E950): https://en.wikipedia.org/wiki/Acesulfame_potassium
* saccharin (E954): https://en.wikipedia.org/wiki/Saccharin
* psicose, aka allulose (0.2 Kcal/g): https://en.wikipedia.org/wiki/Psicose

**Comment by CharlesNepote** [comment]
Many products with low energy (less than 13 Kcal or 55 Kj) are facing this error, probably due to rounded numbers.
See:
* https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=4056489024354#nutrition
*  https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=8480000073136#nutrition
etc.

**Comment by alexgarel** [comment]
Another case where we should exclude computation is when we have <0,5 quantities (at least too much of them) for it does not seems to work.

ex: 
* https://world-fr.openfoodfacts.org/produit/3564700737194/jus-de-citron-de-sicile-rustica
* https://world-fr.openfoodfacts.org/produit/4056489009412/jus-de-citron-vert-solevita

**Comment by benbenben2** [comment]
What do you want to implement exactly?

1) Shutdown the error if category is swettener
2) shutdown the error if energy kj or energy kcal are lower than 55 and 13, resepctively.
Something else?


--------------------

Note for 2)
> Many products with low energy (less than 13 Kcal or 55 Kj) are facing this error, probably due to rounded numbers.

119 006 products with "energy-kj_100g" < 55 or "energy-kcal_100g" < 13 among them:
- 118 078 products WITHOUT energy-value-in-kcal-does-not-match-value-in-kj error
- 928 products having energy-value-in-kcal-does-not-match-value-in-kj error

[Mirabelle](https://mirabelle.openfoodfacts.org/products?sql=select+*+from+%5Ball%5D+WHERE%0D%0A--+119+006+rows%0D%0A%28%22energy-kj_100g%22+%3C+55+or+%22energy-kcal_100g%22+%3C+13%29+--+%22or%22+instead+of+%22and%22+is+okay+because+1%29+if+reversed+there+is+another+error%2C+2%29+if+only+cal+and+wrote+in+kj+instead+of+kcal%2C+then+it+will+be+%3C+55+instead+of+%3C+13%2C+there+should+be+no+false+positives%0D%0A--+++118+078%0D%0AAND+data_quality_errors_tags+NOT+LIKE+%22%25energy-value-in-kcal-does-not-match-value-in-kj%25%22%0D%0A--++928%0D%0A--AND+data_quality_errors_tags+LIKE+%22%25energy-value-in-kcal-does-not-match-value-in-kj%25%22%0D%0AORDER+BY+random%28%29+limit+100)
