### ISSUE TITLE
Wrong redirection for some products

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7823]
### Describe the bug

https://world.openfoodfacts.org/cgi/search.pl?search_terms=35%25+Fruit+And+Fiber+Muesli&search_simple=1&action=process

=> found https://world.openfoodfacts.org/product/0000000031233/35-fruit-and-fiber-muesli-golden-temple

=> cliking on the link leads to https://world.openfoodfacts.org/product/00031233/super-chicken-spinach-quinoa-marks-and-spencer

There seem to have other errors. Eg.  see this list: https://world.openfoodfacts.org/state/brands-to-be-completed/code/000000003xxxx

**Comment by stephanegigandet** [comment]
It's probably because we changed the normalization of barcodes at some point:

```
		# Remove 5 or 6 leading 0s for EAN8
		# 00000080050100 (from Ferrero)
		if ((length($code) eq 14) and ($code =~ /^000000/)) {
			$code = $';
		}
		if ((length($code) eq 13) and ($code =~ /^00000/)) {
			$code = $';
		}
```

codes that have only 5 digits that are non zeros are internal codes, and it's very likely that some of them will conflict with other products from other stores/brands.

we probably should remove most of them... those for instance:

![image](https://user-images.githubusercontent.com/8158668/206715562-647b4435-a866-4544-aded-916ab71596d0.png)

**Comment by stephanegigandet** [comment]
Those are from an old import of usda-ndb-import in 2018.

**Comment by alexgarel** [comment]
see https://github.com/openfoodfacts/openfoodfacts-server/issues/7249 and https://github.com/openfoodfacts/openfoodfacts-server/issues/7248 which should bring a solution to that.
