### ISSUE TITLE
Packaging section sometimes does not show anything

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#7964]
### Describe the bug

As you can see from the image below, although the section is expanded there is nothing in there.

### To Reproduce

1. Go to https://it.openfoodfacts.org/product/8001120971814/orzo-solubile-biologico-coop
2. Try to open the packaging section

### Expected behavior

The packaging section should show the inputted values

### Screenshots

![immagine](https://user-images.githubusercontent.com/12072630/211201267-ad8a9f18-4dc0-47f5-a86e-0bd6ca5a9c16.png)

### Additional context

Also, this is the DOM:

```html
<h3 id="panel_group_packaging_recycling" class="panel_title_card">Confezionamento</h3>
<!-- start templates/web/panels/panel.tt.html - panel_id: packaging_recycling -->
<ul data-accordion="" class="panel_accordion accordion" id="panel_packaging_recycling" style="margin-top:0.5rem;margin-bottom:1.5rem;">
   <li class="accordion-navigation active">
      <a href="#panel_packaging_recycling_content" class="panel_title" aria-expanded="true">
         <img src="https://static.openfoodfacts.org/images/icons/dist/packaging.svg" style="height:72px;float:left;margin-right:1rem;" alt="icon" class="filter-red">
         <h4 class="evaluation_bad_title">
            Imballaggio ad alto impatto
         </h4>
         <hr class="floatclear">
      </a>
      <div id="panel_packaging_recycling_content" class="content panel_content active">
      </div>
   </li>
</ul>
<!-- end templates/web/panels/panel.tt.html - panel_id: packaging_recycling -->

```

### Type of device

Browser

### Browser version

Firefox 108.0.2

**Comment by stephanegigandet** [comment]
This is because we initially had only "en:recycle" and "en:discard" as recycling instructions in the packaging_recycling taxonomy, but then many others were added.

Corresponding file: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/api/knowledge-panels/environment/packaging_recycling.tt.json

[% FOREACH recycling_type IN ["en:recycle", "en:discard", "en:unknown"] %]

So for this product, we don't display the packaging components because they have other recycling instructions.

We need to change the logic so that we can show other recycling types.

**Comment by alexgarel** [comment]
@deveshidwivedi has tested that it's now fixed. Thanks :-)
