### ISSUE TITLE
Edition mode: sometimes nutrients are not displayed while they exist

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7991]
### Describe the bug

When coming to "Nutrition facts" section, the values are not displayed.

When clicking on `[ ] Nutrition facts are specified for the product as sold.` checkbox, the values appear.

### To Reproduce

Eg. https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=3100080000444
![image](https://user-images.githubusercontent.com/562352/212672501-78404def-ea4f-4482-9532-5d1b55f5fefb.png)

Tested on Firefox and Chrome (without any plugin or user script). Nothing special in my browser console...

**Comment by alexgarel** [comment]
@CharlesNepote the solution is  to hide the nutrition table in this case. (it makes no sense displaying it if no information is provided).

**Comment by alexgarel** [comment]
See https://world.openfoodfacts.org/api/v2/product/3100080000444?fields=nutrition_data nutrition data was really said not to exists on the product.

We might have a quality warning though in this case: nutrition photo selected but no nutrition data.

**Comment by CharlesNepote** [comment]
> @CharlesNepote the solution is to hide the nutrition table in this case. (it makes no sense displaying it if no information is provided).

But information IS provided, both on the product AND in the database.

> See https://world.openfoodfacts.org/api/v2/product/3100080000444?fields=nutrition_data nutrition data was really said not to exists on the product.

Yes but the checkbox `[ ] Nutrition facts are not specified on the product.` is unchecked => see photo =>
![image](https://user-images.githubusercontent.com/562352/213165536-1ab0ffb1-6e11-473d-ba8e-aec4af119121.png)

And if you click on `[ ] Nutrition facts are specified for the product as sold.` checkbox, the values appear.

**Comment by alexgarel** [comment]
Ok so we should display an error if the one above is unchecked and we do not check any of the below ?

Or should we automatically check the one above in this case (and hide the panel ?)

**Comment by CharlesNepote** [comment]
First, here are some data, made possible thanks to the recently fixed `no_nutrition_data` field from the CSV export:
* [58,000+ products](https://mirabelle.openfoodfacts.org/products?sql=select+count%28no_nutrition_data%29%0D%0Afrom+simplified%0D%0Awhere+no_nutrition_data+%21%3D+%22%22%0D%0Alimit+21) have the field `no_nutrition_data` specified.
* I thought the value should be `on` or `""` but [there are](https://mirabelle.openfoodfacts.org/products/simplified?_facet=no_nutrition_data):
  * `on`: 24,910
  * `off` 16,877
  * `null`: 7,755
  * `true`: 7,037
  * `false`: 1,619
* [5,000+ of the products](https://mirabelle.openfoodfacts.org/products?sql=select%0D%0A%28select+count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22on%22%29%29+as+no_nutrition_data_on%2C+%0D%0A%28select+count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22on%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_on_and_fat100%2C%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22true%22%29%29+as+no_nutrition_data_true%2C%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22true%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_true_and_fat100) with `no_nutrition_data == "on"` or `no_nutrition_data == "true"` also has fat_100g filled
* Here is a [full table with all the existing values and whether fat_100g exists](https://mirabelle.openfoodfacts.org/products?sql=select%0D%0A%0D%0A%28select+count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22on%22%29%29+as+no_nutrition_data_on%2C+%0D%0A%0D%0A%28select+count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22on%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_on_and_fat100%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22true%22%29%29+as+no_nutrition_data_true%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22true%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_true_and_fat100%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22off%22%29%29+as+no_nutrition_data_off%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22off%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_off_and_fat100%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22null%22%29%29+as+no_nutrition_data_null%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22null%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_null_and_fat100%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22false%22%29%29+as+no_nutrition_data_false%2C%0D%0A%0D%0A%28select++count%28no_nutrition_data%29+from+simplified+where+true+%0D%0Aand+%28no_nutrition_data+%3D%3D+%22false%22%29%0D%0Aand+fat_100g+is+not+null%29+as+no_nutrition_data_false_and_fat100%0D%0A)

I don't know where to start but we must think a little bit.

- [ ] First I would check Product Opener code and our mobile app code to see what's entered in the DB
- [ ] Then I would check randomly why people are entering `on` or `true` when fat_100g exists

But all of this have nothing to do with the issue I mentioned, which was a display issue!

**Comment by alexgarel** [comment]
We talked about it today… @CharlesNepote is it a most wanted issue ?

**Comment by teolemon** [comment]
- For me it's a P0. It's making web edition totally unintuitive (you have to tick a box to get nutrients on most products)
- we should instrument editing as matomo events to measure such regressions

**Comment by garu** [comment]
Hi! I have two possible solutions to be considered:

1.
<img width="616" alt="OFF-7991" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/52187/f4810226-f129-4226-9721-0953ac57c0dd">

It completely eliminates the checkboxes, which I assumed were there to allow moderators to hide nutrition data for incomplete or incorrect entres without having to delete the data. Both columns on the nutrition table are always visible during edit, but once the change is saved the actual page will only show columns with at least one row containing data. Note that the radio buttons are moved to the table header to make their intent clearer.

This approach has the following side-effects:
  * because the checkbox is gone, all items on the database with at least one nutrient row filled will immediately have its nutrition table shown, regardless of wether the checkbox was checked or not.
  * because the checkbox is gone, it is important to make sure their value (the `nutrition_products` array) is not used elsewhere, in order to prevent regressions and odd behaviours outside this page.

2.
<img width="571" alt="OFF-7991-option2" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/52187/2459937b-a141-49a0-8cfd-d64a194ac090">

Similar to option 1 above, but keeps the checkboxes, rewording them a little for clarity. Instead of disappearing, the entire column is marked in a way that makes it clear that it will not be shown to users (in the example above I added diagonal stripes, but it could be a solid colour or pretty much anything we want).

I like this option best because moderators will still be able to easily hide nutrition facts that are though of as incomplete or incorrect without having to delete them, and editors will still quickly understand what is going on and perhaps even how to fix any incomplete data. Also, by keeping the checkboxes, we ensure no side-effects happen elsewhere in the code, since it will function just like it is today.

The only side-effect is the new text will need to be translated.

If one of the proposed solutions is accepted for this issue, I'll gladly send a PR with the changes. Otherwise, please let me know if I missed something, if you require some tweaks to the proposed solutions or if you rather approach this differently 🙃

**Comment by stephanegigandet** [comment]
> It completely eliminates the checkboxes, which I assumed were there to allow moderators to hide nutrition data for incomplete or incorrect entres without having to delete the data.

In fact the checkboxes remove the data (at least on the web UI), you can see it if you uncheck and then check the box again.

My initial intention was to display only the "As sold" column by default, as it is the only one present on most products, to avoid cluttering the page with an extra column that would not be used (and possibly to avoid confusing users: we don't want them to fill the prepared column by just copying the unprepared values for cookies for instance).

I think both options are improvements on the current situation, but I prefer option 1 as it removes the possibility of having incoherent data (checkbox unchecked, but some existing data).

**Comment by garu** [comment]
so there is a third solution, which is to 

3. keep everything as is *but* even if no data is available, check the "as sold" box by default anyway so it shows the (empty) column to be filled.

And it that case, fix the issue where items have nutrition facts but their checkbox is unchecked in edit mode. for consistency, any products in edit mode that have nutrition facts should start with their checkboxes properly marked.

is solution 3 the best? are there any other unconsidered solutions here that should be explored? or should we move on and implement 1?

**Comment by stephanegigandet** [comment]
Maybe we could have a mix of 1 and 3:

1. We could move the (per 100g / per serving) radio buttons in the column headers as in 1, I think that's a great idea.
2. We stop saving the checkboxes states as fields in the database:
- we keep only the nutrients values: either we have values, or we don't, we do not need an extra field to say that we have nutrients or not
- we show only the columns for which we do have data
- if we don't have data at all, we show the as_sold column
- we show the 2 checkboxes so that we can add a column
- the checkboxes can be unchecked to hide a column only if there are no values in that column

What do you think?

**Comment by alexgarel** [comment]
I think the last Stephane proposal is good. :+1: also for contextual help.

**Comment by CharlesNepote** [comment]
I have an interesting example of this bug here: https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=7032069736708

The product has been created a few days ago by one person using the Open Food Facts mobile app. No other tool has modified this product. Consequently, the issue comes from either the app, either Product Opener.

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/562352/bba583cf-5114-46da-b6d3-628ea90d16eb)

**Comment by stephanegigandet** [comment]
@CharlesNepote interesting indeed. We have a string "null" value: nutrition_data: "null",
