### ISSUE TITLE
RDF Data Export seems broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#811]
```I was wondering if there was any contributors currently working on improving and correcting the RDF database of OpenFoodFacts.
If yes, is there a way to be in contact with them or a discussion about what and how they are working on it?```

**Comment by rogargon** [comment]
RDF data is broken. The EN and FR versions include URL with whitespaces. The ES version is missing.

For instance, trying to load the data into Virtuoso:

```
dumps/en.openfoodfacts.org.products.rdf | https://world.openfoodfacts.org/data | 2 | 2019-01-29 12:17:14.528896 | 2019-01-29 12:17:14.607020 | 0 | <DB NULL> | 22007 XM033: XML parser detected an error: ERROR : Syntax error in the attribute list (no whitespace) at line 14074 column 30 of source text <food:food rdf:resource="http://fr.openfoodfacts.org/ingredient/fr:Viter l' ----------------------------^
dumps/fr.openfoodfacts.org.products.rdf | https://world.openfoodfacts.org/data | 2 | 2019-01-29 12:50:39.451954 | 2019-01-29 12:50:39.525361 | 0 | <DB NULL> | 22007 XM033: XML parser detected an error: ERROR : Syntax error in the attribute list (no whitespace) at line 14074 column 30 of source text <food:food rdf:resource="http://fr.openfoodfacts.org/ingredient/fr:sin aler ----------------------------^
```

**Comment by CharlesNepote** [comment]
Thanks @rogargon. The RDF is an old export not very well maintained. Olivier Rossel on twitter said he wrote an good exporter based on the CSV, see: https://twitter.com/datao/status/1086213152327516160 (in french).

This bug is not a high priority for us. I'll try to have a look but I can't garanty when it's done. In case you know a bit of Perl, the export script is here:
https://github.com/openfoodfacts/openfoodfacts-server/blob/1d4063feaedc759543419227403c66cfa6658029/scripts/export_database.pl

Ready to use solutions welcome ;-) (Pull request or whatever.)

**Comment by CharlesNepote** [comment]
@rogargon: @lolive has just published his scripts here: https://github.com/lolive/openfoodfacts-rdf

For the CSV alternative there is a good article here related to injecting the CSV in PostgreSQL: http://blog-postgresql.verite.pro/2018/12/21/import-openfoodfacts.html (french but should be ok for Google Trad).

**Comment by lolive** [comment]
Some more information are available at this Twitter thread: https://twitter.com/datao/status/1090593164241616896?s=21

**Comment by teolemon** [comment]
Closing this one since @CharlesNepote fixed it
