### ISSUE TITLE
Improve the discoverability of the Pro Platform 

### ISSUE THREAD

**Issue by manon-corneille** [openfoodfacts/openfoodfacts-server#8332]
Today, it's quite difficult to discover the Producers' platform from https://world.openfoodfacts.org/

A simple way to improve its discoverability would be to add a link in the header menu : 

![image](https://user-images.githubusercontent.com/104015489/232833048-695d4f9a-19ef-48b9-9b7f-0d6006b00a47.png)

### Part of
- #5521

**Comment by manon-corneille** [comment]
Hi all, I just checked and it seems it hasn't been deployed on all languages: 
* https://fr.openfoodfacts.org/ → OK
* https://de.openfoodfacts.org/ → OK 
* https://it.openfoodfacts.org/ → **Not OK** 
* https://es.openfoodfacts.org/ → **Not OK** 
* https://world.openfoodfacts.org/ → **Not OK** 
* https://nl.openfoodfacts.org/ → **Not OK** 

Would it be possible to add the link to the Pro platform it in those countries too please?

**Comment by MonalikaPatnaik** [comment]
Hii @manon-corneille, I think the last three links are working fine and redirecting to the pro platform of their respective languages, I am not sure about [https://world.pro.openfoodfacts.org/](https://it.openfoodfacts.org/) , as it is redirecting to [https://world.pro.openfoodfacts.org/]( https://world.pro.openfoodfacts.org/)

**Comment by manon-corneille** [comment]
Hi @MonalikaPatnaik - I'm surprised, on my side I can't see the "Producers" button. 
Here is a screenshot from the https://world.openfoodfacts.org/  :) 
<img width="1360" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-server/assets/104015489/46a47b54-65b4-48f3-b7cb-c7c30db77d1c">

Do you see something different on your side maybe?

**Comment by manon-corneille** [comment]
After discussing with @MonalikaPatnaik it turns out we don't see the same result: she sees the button on her browser, and I don't. I tested with incognito and I don't see the button. 

@stephanegigandet or @alexgarel  any idea why this would be? 

Thx

**Comment by stephanegigandet** [comment]
@manon-corneille That's because we only display the Producers link if the screen is wide enough:

`<li class="show-for-xlarge-up"><a href="https://world.pro.openfoodfacts.org/" class="top-bar-links">Producers</a></li>`

On a large screen, the link is shown, and if the window is reduced, it is removed at some point.

xlarge is 1441 px wide and larger.

Note that in some languages "Discover", "Contribute" and "Producers" are translated to longer strings, so while we may have space in English, it's not guaranteed that it wouldn't cause issues in other languages.

**Comment by manon-corneille** [comment]
I see, thank you for the detailed explanation :)
