### ISSUE TITLE
Fixing Pro Docs

### ISSUE THREAD

**Issue by MonalikaPatnaik** [openfoodfacts/openfoodfacts-server#8509]
### Describe the bug

`make_build_lang` and `make restart` seems not working in pro shell in order to load the CSS etc rather it runs only on non pro shell.
Also, in order to access the pro platform in localhost we have to run a series of commands like `docker exec -it po_pro-backend-1 bash` , `cd scripts` , `./build_lang.pl `, `docker compose stop backend` and  `docker compose start backend` ( verified that it works). 

### To Reproduce

Will add detailed steps and commands to be executed in the producers environment in order to run the necessary containers of the pro shell and access the platform in localhost.

### Expected behavior

We can now be able to view the complete pro platform in our localhost.

### Type of device

Browser

### Browser version

114.0.5735.90

### Part of
- #7744 
- #5521

**Comment by alexgarel** [comment]
Hum, I think there is a way we could make it work with Makefile 

It's not accounted because [we load `.env` file at the begining](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/Makefile#L34)

So we could find a way to detect that we are in a *pro* shell ( PRODUCERS_PLATFORM is 1) and source the setenv-pro.sh before running docker commands maybe ? It's a bit subtle to handle though, as every line of a Makefile runs in it's own shell… I'm not sure about the best way to handle that.

**Comment by manon-corneille** [comment]
Is this still a problem or should we close the issue? @MonalikaPatnaik :)

**Comment by alexgarel** [comment]
Summary: change the Makefile to detect (through env variables) that we are in pro shell and load right file in this case

**Comment by alexgarel** [comment]
This was already done, see 05c75f46d0ade2c54f9dde822936a0723c753c35
