### ISSUE TITLE
Should producers be able to self-delete accounts from the Pro Platform ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8638]
### What
- Should producers be able to self-delete accounts from the Pro Platform ?

**Comment by manon-corneille** [comment]
I'd say yes. Today, I give them the list of users and they tell me what account to delete. 
It would be faster if they were autonomous on that front. 
Also, as long as they belong to the organisation I don't see what harm they could cause so I think it's a good idea. 

We could maybe build up on this feature: https://github.com/openfoodfacts/openfoodfacts-server/pull/8511 and the option de delete account from this table?

**Comment by stephanegigandet** [comment]
We would need to add a special admin role for users associated with an organization, so that they can see other organization members, and delete them, and ideally they  would also need a button to invite users to their organization. We could keep track of invites, and when a new user creates an account with that email address, he/she gets added to the organization.

**Comment by manon-corneille** [comment]
I really like the idea of being able to invite other members, as it would save some time (the time we spend manually validating accounts to join an org). 👍
