### ISSUE TITLE
User is not able to edit products from the web interface

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-server#8644]
### Description
User has reported being unable to edit the product. In particular, after opening edit mode, changing a value and saving, the product is not updated despite an "entry" being created in the product history.

[Read the forum post for more details.](https://forum.openfoodfacts.org/t/impossible-to-edit-the-nutrition-information-of-some-products/316/1)

See for example edits:
- https://world.openfoodfacts.org/product/3560070485406/filets-de-cabillaud-carrefour?rev=50
- https://world.openfoodfacts.org/product/3560070485406/filets-de-cabillaud-carrefour?rev=51

### Acceptance criteria

The user should be able to edit a product via the web interface.

### Notes
Debugging cases like this should be easier with a "diff" mode. Do we have anything like that? Even in the API?

### Part of epic
- #525

**Comment by fgouget** [comment]
I reported this issue on the [forums initially](https://forum.openfoodfacts.org/t/impossible-to-edit-the-nutrition-information-of-some-products/316/7) and VaiTon was kind enough to report it here so it can be tracked properly.

Here are some additional details:
* There are products I can edit and others I cannot.
* Other users seem to be able to edit the products I cannot. They don't report any difficulty doing so. See:
  https://forum.openfoodfacts.org/t/les-corrections-impossibles-aide-bienvenue/333
* I tried editing from both world.openfoodfacts.org and fr.openfoodfacts.org. Same results. See:
  world: https://world.openfoodfacts.org/product/3073781099621/boursin-ail-fines-herbes?rev=85
  fr: https://fr.openfoodfacts.org/produit/3073781099621/boursin-ail-fines-herbes?rev=86
  Notice how these two changesets say "Changed: categories, labels" and yet, I changed neither the category, nor the labels, instead I went directly to the nutritional table and only changed the kJ, kcal, Sugars and Proteins values, and yet none of these are listed.
* This issue is not limited to the nutritional table. For instance I was unable to fix the name of this product, yet someone had no problem doing so yesterday:
  failed edit: https://world.openfoodfacts.org/product/3073781099621/boursin-ail-fines-herbes?rev=82
  successful edit: https://world.openfoodfacts.org/product/3073781099621/boursin-ail-fines-herbes?rev=84
* I usually use Firefox (currently 114.0.2, Linux) but I had the same result with Chromium (113.0.5672.126, Linux), the new Android App (4.7.0 on a Samsung Galaxy S7, SM-G930F, Android 8.0.0), and the old Android app (which I no longer have).
* I have the same issue in a newly created account (fgouget2). The changeset below should have modified the nutritional table but did not (instead the changeset says I modified "origins" which I did not):
   https://world-fr.openfoodfacts.org/produit/3560070485406/filets-de-cabillaud-carrefour?rev=63
* As far as I can tell, even when my updates are dropped, the image updates I send from the app are taken into account. I did not do a thorough check but I never noticed an outdated nutritional table picture even when I cannot update the nutritional information itself.
* This has been going on for months but it feels it has become worse in the past weeks. Initially I thought it was specific to the Android App (F-Droid's 3.x at the time which was very crashy too) because I was able to do the edits on the web site. Now nothing works for me (I can't keep asking other users to do the edits for me on the forums).

**Comment by alexgarel** [comment]
Very strange… sorry for the inconvenience @fgouget.

I quickly checked the edit_rules, to see if it could be that, but I don't think so.

Could you check if you are able to reproduce it on https://fr.openfoodfacts.net ? (off / off). If that's the case we might be able to try to see the logs at the moment you encounter the problem.
