### ISSUE TITLE
Add last_updated_t for silent updates (in addition to existing last_modified_t for new product revisions)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#8860]
We currently have a last_modified_t field that is set when we create a new product revision.
This field is not updated when we have "silent" updates that do not create new revisions (e.g. when we re-process ingredients or packagings, recompute scores etc.).

We could create a new last_updated_t field for those silent updates.

This could in particular be very useful for updating copies of the "source" OFF data: alternate mongodb collections, postgres databases, CSV exports etc.

**Comment by john-gom** [comment]
We should also push to the redis stream in this case too for subscribers like search-a-licious and off-query

**Comment by CharlesNepote** [comment]
I reopen this, as #9428 did not solve the issue. @stephanegigandet was mentioning:
> This could in particular be very useful for updating copies of the "source" OFF data: alternate mongodb collections, postgres databases, CSV exports etc.

In data quality day-to-day tasks it can be important to know what have changed since some time.
This is also a need if we want to provide historized exports, such as currently tested in #7660.

`last_updated_t` should be also exported in the CSV as `last_updated_datetime`.

**Comment by alexgarel** [comment]
Done in #9646
