### ISSUE TITLE
Make it possible for a user to retrieve his user id

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8892]
### Problem

As stated [on slack](https://openfoodfacts.slack.com/archives/C02KVRT2C/p1692634662253639) by a user, it's very hard to retrieve your user id. It only appears in the urls.

It should be easy for a user to know his userid.

### Proposed solution
Display the user id in the "account parameters" page.

### Code pointers

see cgi/user.pl which use a template (see at the end). Just add userid it in the template context and display it in the template.

      
Part of:
- #5809

**Comment by himanshi-154** [comment]
I would like to work on this issue!

**Comment by TheSussex** [comment]
Hi @alexgarel, can you confirm if this issue is stale or not? I'm a bit confused because I went through the problem description and tried to recreate on my end but I see that the userid already exists on the **Account Parameters** page hence why I want to know if it still needs some work. _See screenshot for reference._

Also, should the field be called `username`? Isn't `userid` more descriptive especially because that's what brought up the issue in the first place.

![Uploading Screenshot 2024-03-15 at 9.58.35 AM.png…]()

**Comment by TheSussex** [comment]
Hi @alexgarel, can you confirm if this issue is stale or not? I'm a bit confused because I went through the problem description and tried to recreate on my end but I see that the userid already exists on the **Account Parameters** page hence why I want to know if it still needs some work. _See screenshot for reference._

Also, should the field be called `username`? Isn't `userid` more descriptive especially because that's what brought up the issue in the first place.

**Comment by himanshi-154** [comment]
@TheSussex I am already working on this issue, thanks!

**Comment by alexgarel** [comment]
I think it was fixed some times ago ! Thanks for reporting.

**Comment by stephanegigandet** [comment]
> Also, should the field be called `username`? Isn't `userid` more descriptive especially because that's what brought up the issue in the first place.

That's a good point, I will file another issue.

**Comment by stephanegigandet** [comment]
Filed https://github.com/openfoodfacts/openfoodfacts-server/issues/9942

**Comment by john-gom** [comment]
Keycloak supersedes this
