### ISSUE TITLE
Non vegan additives should trigger non vegan status

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8918]
### What
![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/1689815/f81371c6-aaaa-4da4-81ff-a92830d7aa40)
https://world.openfoodfacts.org/additive/e542-bone-phosphate
https://world.openfoodfacts.org/product/15440761/bion-3

### Part of
- #5706

**Comment by stephanegigandet** [comment]
Non vegan additives already trigger non vegan status, the product you link to has a completely broken ingredients list and we detect an additive that is not there (additive detection works in a different way than ingredients detection).

There's another Russian product where the issue is that we don't have a Russian translation, adding xx: entries should solve it.
