### ISSUE TITLE
Be more granular on Photo selection state

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#898]
In addition to photo-to-be-validated, add: 
```
nutrition-photo-to-be-validated
ingredients-photo-to-be-validated
front-photo-to-be-validated
```

It will enable selective quests and tasks

**Comment by hangy** [comment]
Would it be OK to have the `front-photo-to-be-validated` state if a product has ie. French and German language information, if it does not have a German front picture, even though it does have a French front picture?

**Comment by hangy** [comment]
FWIW, I think the photo validity state does not work too well with multiple languages on a product, yet.

If I understand this correctly
https://github.com/openfoodfacts/openfoodfacts-server/blob/aab662fcc4febf6a87b26631ccb63292fcaa1c90/lib/ProductOpener/Products.pm#L407-L417
would only check the current UI language, so that a product that was marked completed in French, would suddenly be incomplete (with missing images) when edited in German UI language.

This should probably be reworked to iterate over all languages either way. An open question would be, if adding a separate state (`nutrition-photo-to-be-validated-*de*`) for all added languages would be useful or if would just make the states facet unsable.

**Comment by teolemon** [comment]
I think it would be useful. I'd like to be able to generate printable lists of products for which we need photos or updated photos.
https://world.openfoodfacts.org/store/auchan/state/ingredient-photo-to-be-completed
https://world.openfoodfacts.org/store/auchan/state/ingredient-fr-photo-to-be-completed

**Comment by teolemon** [comment]
This one is fixed @hangy 
I've opened a new issue with your relevant comment.
