### ISSUE TITLE
Implement a Recent Changes page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#908]
https://wikidata.org/wiki/Special:RecentChanges
![image](https://user-images.githubusercontent.com/1689815/31374855-ecbb60b6-ad9f-11e7-8074-5bfe1a547ed4.png)
![image](https://user-images.githubusercontent.com/1689815/31374870-fb62d4a0-ad9f-11e7-99cf-1b941896f31f.png)

Wikidata does a streaming live version of changes with Color Codes, a quick diff link to see what has changes, and the contributor responsible for it.

**Comment by hangy** [comment]
Basically, we could hook into `Products::store_product` and store the product code, username, old revision number, new revision number, and current time in an additional MongoDB collection. That could be queried pretty efficiently to display the "latest" changes. Maybe add the affected countries to this helper/changes collection, so that different countries get their own changes. Anything else that I'm missing?

**Comment by hangy** [comment]
> Probably add product name in all languages

+Product countries to filter recent changes by the selected region
