### ISSUE TITLE
Wipe the vegan label if there's a non vegan ingredient in the ingredient list

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#913]
Wipe the vegan label if there's a non vegan ingredient in the ingredient list

**Comment by TaciteOFF** [comment]
The « Vegan » label is a label. With an official logo. So if it’s not on the packaging, it shouldn’t be on the product page.
Many ingredients are tricky, can be vegan or not, like « aromas ». 
Also, the Spanish « Vegadona » association uses OFF for its actions on social media, cleaning the database can lead to a conflict. 
In the past, discussions have already been initiated with Javichu, one of their members, without success.

**Comment by hangy** [comment]
The labels are not limited to stuff that's official. Of course, we have labels like [EU Organic](https://world.openfoodfacts.org/label/eu-organic) or [Green Dot](https://world.openfoodfacts.org/label/green-dot), which require certain criteria to be met. On the other hand, there is [low fat](https://world.openfoodfacts.org/label/low-fat) which everyone can claim.

From my understanding, the original idea of OFF is to enter the data as it is presented on the packaging, so that vendors' claims can be matched against other criteria. (For example, a "low fat" yoghurt might have more fat than other yoghurts, so that everyone can see that this label is invalid.) Using that logic, the vegan label should be kept if it is on the packaging, even if the ingredients list contains [ham](https://world.openfoodfacts.org/ingredient/ham)?

**Comment by jolesh** [comment]
I don't know if it is a good idea to do it automatically because there are also erros in the ingredient lists like "Frucht - fleisch"(en:"fruit - meat") instead of "Fruchtfleisch". So I think it would be better ask users "Is this really vegan? Looks like there is animal product "X" in it."

**Comment by benbenben2** [comment]
FYI @teolemon, there is now a quality error for that: https://github.com/openfoodfacts/openfoodfacts-server/pull/9063
That may close this issue?

**Comment by alexgarel** [comment]
Let's close (@teolemon agree).
