### ISSUE TITLE
Can we disable Snyk protect ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9353]
### What
- I'm not sure what Snyk protect has ever done for us, and why we need to update it almost daily
- https://github.com/openfoodfacts/openfoodfacts-server/pull/9351
- I'd be in favor of disabling it since it eats some validation time (50s each day)

**Comment by hangy** [comment]
> I'm not sure what Snyk protect has ever done for us

It's supposed to update vulnerable npm packages, but I agree that it hasn't done a lot in this repo.

> why we need to update it almost daily

I'd be in favour of reducing all dependabot intervals to weekly. https://github.com/openfoodfacts/openfoodfacts-server/blob/c36f8db9bbfec28e34aabac41fdf476f9fc82138/.github/dependabot.yml#L8C21-L8C21 With our current release model, there's little use to have daily updates.

> I'd be in favor of disabling it

Since we also have dependabot doing some security updates, I currently don't see why not.

**Comment by teolemon** [comment]
Closing, as mitigated
