### ISSUE TITLE
New knowledge panels properties: half size panel + very short title and description

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#9368]
On mobile (app + web) we want to show some panels in a more condensed way, 2 by 2:

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/8158668/b2bf27a1-63ea-4471-bcbc-65de1b147178)

We need to define new properties for specifying that the panel should be shown half size on mobile, and add very short titles and descriptions.

### Part of
- #8919

**Comment by monsieurtanuki** [comment]
@stephanegigandet @alexgarel Data that is currently missing from the server side that I've noticed in https://github.com/openfoodfacts/smooth-app/pull/4890 (about the Nutriscore panel only):
* The localized short title, e.g. "Sugars" (for the moment we have something like "Sugars in big quantity") (already mentioned in the OP)
* The localized grade, e.g. "Poor" (for the moment we have something like "Poor nutritional value") (somehow already mentioned in the OP)

Besides, assuming that the percentage is the percentage of nutrient quantity in grams:
* We would need the value as a `double`
* Meanwhile I've managed to compute the value from the product nutrition facts
* Currently the decimal separator is not localized (e.g. for "Sucre : 1.2%" and not "Sucre : 1,2%") (current bug en passant, we won't care anyway if we have the `double` field)
* It's a bit confusing to see for each nutrient the percentage and colors that don't match (e.g. Fat 16% is orange and Saturated fat 11% is red)
* a11y sucks in the screenshots, because only the colors show the importance, which is not user-friendly for color-blinds

**Comment by john-gom** [comment]
I've started looking into this (also referring to https://github.com/openfoodfacts/smooth-app/issues/4889). Initial observations:

There seem to be three pieces of information that need to be conveyed:

1. Short name of the attribute, e.g. "Saturated fat", "Packaging", etc.
2. Value for that attribute, e.g. "11%", "High impact"
3. Indication of whether the value is good, bad or average (in order to colour the text)

For the name of the attribute, this should already exist and be consistent with the name used when users are selecting their food [preferences](https://world.openfoodfacts.org/api/v0/attribute_groups).

For the value of the attribute I'm not sure a double is going to work for attributes like Packaging and Species threat, so it may be we need to keep this as text (and fix the decimal separator on the server side).

It looks like the existing undocumented "evaluation" property could be used to indicate good / bad.

**Comment by john-gom** [comment]
Update. We already have a "type" to indicate grade, so expanding this to include "percentage" allows the value to be supplied as a raw number, so regional formatting can be done on the client

**Comment by teolemon** [comment]
- Per @g123k , add an optional parameter to ask for the summarized/condensed version of the Knowledge Panel.

**Comment by alexgarel** [comment]
@teolemon as we have the include / exclude knowledge panels parameters, I would better add a condensed_knowledge_panels=panel1,panel2 etc. which means include the knowledge panel, in condensed form.
