### ISSUE TITLE
[FOUNDATION] Canonical product image URLs

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-server#97]
Right now, all product images of the language subdomains are delivered over those international subdomains. For example, the main image of product [9003740076145](http://de.openfoodfacts.org/produkt/9003740076145/sonnenblumenkerne-ja-naturlich) is

- http://de.openfoodfacts.org/images/products/900/374/007/6145/front.6.400.jpg for the German page, and
- http://world.openfoodfacts.org/images/products/900/374/007/6145/front.6.400.jpg for the Worldwide page.

The images are identical and even use the same ETag. The only difference is the URL that they are available from. Not only for SEO and overall user experience, but also for caching reasons, it might be a good idea to use one canonical URL for all product images instead. For example, all international sites could embed images using the world.openfoodfacts.org domain, and the existing links could redirect the old address to that (301).

**Comment by stephanegigandet** [comment]
Thanks, it will be done in new Foundation redesign.

**Comment by stephanegigandet** [comment]
All images (+ javascript and stylesheets) are now served from a separate static.openfoodfacts.org subdomain. (on the new Foundation design, not yet in production)

The foundation-icons font needs a special header as it is server from a different host than the page's host:

<Location "/foundation/foundation-icons" >
Header set Access-Control-Allow-Origin "*"
</Location>

I used a new static subdomain instead of the world subdomain so that we can use a different IP at some point, e.g. if we want to use a lighter http server for the static files.
